Team.delete_all

Team.find_or_create_by_id(:id => 1,  :name => 'Algeria')
Team.find_or_create_by_id(:id => 2,  :name => 'Argentina')
Team.find_or_create_by_id(:id => 3,  :name => 'Australia')
Team.find_or_create_by_id(:id => 4,  :name => 'Belgium')
Team.find_or_create_by_id(:id => 5,  :name => 'Bosnia-Herzegovina')
Team.find_or_create_by_id(:id => 6,  :name => 'Brazil')
Team.find_or_create_by_id(:id => 7,  :name => 'Cameroon')
Team.find_or_create_by_id(:id => 8,  :name => 'Chile')
Team.find_or_create_by_id(:id => 9,  :name => 'Colombia')
Team.find_or_create_by_id(:id => 10, :name => "Côte d'Ivoire")
Team.find_or_create_by_id(:id => 11, :name => 'Costa Rica')
Team.find_or_create_by_id(:id => 12, :name => 'Croatia')
Team.find_or_create_by_id(:id => 13, :name => 'Ecuador')
Team.find_or_create_by_id(:id => 14, :name => 'England')
Team.find_or_create_by_id(:id => 15, :name => 'France')
Team.find_or_create_by_id(:id => 16, :name => 'Germany')
Team.find_or_create_by_id(:id => 17, :name => 'Ghana')
Team.find_or_create_by_id(:id => 18, :name => 'Greece')
Team.find_or_create_by_id(:id => 19, :name => 'Honduras')
Team.find_or_create_by_id(:id => 20, :name => 'Iran')
Team.find_or_create_by_id(:id => 21, :name => 'Italy')
Team.find_or_create_by_id(:id => 22, :name => 'Japan')
Team.find_or_create_by_id(:id => 23, :name => 'Korea Republic')
Team.find_or_create_by_id(:id => 24, :name => 'Mexico')
Team.find_or_create_by_id(:id => 25, :name => 'Netherlands')
Team.find_or_create_by_id(:id => 26, :name => 'Nigeria')
Team.find_or_create_by_id(:id => 27, :name => 'Portugal')
Team.find_or_create_by_id(:id => 28, :name => 'Russia')
Team.find_or_create_by_id(:id => 29, :name => 'Spain')
Team.find_or_create_by_id(:id => 30, :name => 'Switzerland')
Team.find_or_create_by_id(:id => 31, :name => 'Uruguay')
Team.find_or_create_by_id(:id => 32, :name => 'USA')
