postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
  - '5432:5432'
  volumes:
  - footy-postgres:/var/lib/postgresql/data
footy:
  build: .
  links:
  - postgres
  volumes:
  - .:/footy