unless TOGGLES_CONFIG['five_alive']
  Score.delete_all
  Score.create(id: 1, fixture_id: 1, home: 1, away: 0)
  Score.create(id: 2, fixture_id: 2, home: 0, away: 0)
  Score.create(id: 3, fixture_id: 3, home: 3, away: 0)
  Score.create(id: 4, fixture_id: 4, home: 1, away: 2)
  Score.create(id: 5, fixture_id: 5, home: 0, away: 0)
  Score.create(id: 6, fixture_id: 6, home: 3, away: 4)
  Score.create(id: 7, fixture_id: 7, home: 2, away: 2)
  Score.create(id: 8, fixture_id: 8, home: 1, away: 0)
  Score.create(id: 9, fixture_id: 9, home: 3, away: 1)
  Score.create(id: 10, fixture_id: 10, home: 2, away: 4)

  Score.create(id: 11, fixture_id: 11, home: 1, away: 0)
  Score.create(id: 12, fixture_id: 12, home: 2, away: 2)
  Score.create(id: 13, fixture_id: 13, home: 3, away: 0)
  Score.create(id: 14, fixture_id: 14, home: 1, away: 2)
  Score.create(id: 15, fixture_id: 15, home: 0, away: 0)
  Score.create(id: 16, fixture_id: 16, home: 3, away: 1)
  Score.create(id: 17, fixture_id: 17, home: 2, away: 2)
  Score.create(id: 18, fixture_id: 18, home: 1, away: 0)
  Score.create(id: 19, fixture_id: 19, home: 3, away: 4)
  Score.create(id: 20, fixture_id: 20, home: 2, away: 4)

  Score.create(id: 21, fixture_id: 21, home: 1, away: 2)
  Score.create(id: 22, fixture_id: 22, home: 2, away: 0)
  Score.create(id: 23, fixture_id: 23, home: 3, away: 0)
  Score.create(id: 24, fixture_id: 24, home: 1, away: 2)
  Score.create(id: 25, fixture_id: 25, home: 0, away: 0)
  Score.create(id: 26, fixture_id: 26, home: 3, away: 1)
  Score.create(id: 27, fixture_id: 27, home: 2, away: 2)
  Score.create(id: 28, fixture_id: 28, home: 1, away: 0)
  Score.create(id: 29, fixture_id: 29, home: 3, away: 4)
  Score.create(id: 30, fixture_id: 30, home: 2, away: 4)
end
