Player.delete_all

Player.find_or_create_by_id(id: 1,  team_id: 2  ,name: 'S Aguero')
Player.find_or_create_by_id(id: 2,  team_id: 9  ,name: 'C Bacca')
Player.find_or_create_by_id(id: 3,  team_id: 21 ,name: 'M Balotelli')
Player.find_or_create_by_id(id: 4,  team_id: 31 ,name: 'E Cavani')
Player.find_or_create_by_id(id: 5,  team_id: 15 ,name: 'K Benzema')
Player.find_or_create_by_id(id: 6,  team_id: 29 ,name: 'D Costa')
Player.find_or_create_by_id(id: 7,  team_id: 30 ,name: 'J Drmic')
Player.find_or_create_by_id(id: 8,  team_id: 5  ,name: 'E Dzeko')
Player.find_or_create_by_id(id: 9,  team_id: 7  ,name: "S Eto'o")
Player.find_or_create_by_id(id: 11, team_id: 31 ,name: 'D Forlan')
Player.find_or_create_by_id(id: 12, team_id: 6  ,name: 'Fred')
Player.find_or_create_by_id(id: 13, team_id: 14 ,name: 'S Gerrard')
Player.find_or_create_by_id(id: 14, team_id: 15 ,name: 'O Giroud')
Player.find_or_create_by_id(id: 15, team_id: 16 ,name: 'M Gotze')
Player.find_or_create_by_id(id: 16, team_id: 9  ,name: 'T Gutierrez')
Player.find_or_create_by_id(id: 17, team_id: 4  ,name: 'E Hazard')
Player.find_or_create_by_id(id: 18, team_id: 2  ,name: 'G Higuain')
Player.find_or_create_by_id(id: 19, team_id: 6  ,name: 'Hulk')
Player.find_or_create_by_id(id: 20, team_id: 25 ,name: 'K Jan Huntelaar')
Player.find_or_create_by_id(id: 21, team_id: 16 ,name: 'M Klose')
Player.find_or_create_by_id(id: 22, team_id: 2  ,name: 'E Lavezzi')
Player.find_or_create_by_id(id: 23, team_id: 4  ,name: 'R Lukaku')
Player.find_or_create_by_id(id: 24, team_id: 2  ,name: 'A di Maria')
Player.find_or_create_by_id(id: 25, team_id: 9  ,name: 'J Martinez')
Player.find_or_create_by_id(id: 26, team_id: 2  ,name: 'L Messi')
Player.find_or_create_by_id(id: 27, team_id: 16 ,name: 'T Muller')
Player.find_or_create_by_id(id: 28, team_id: 6  ,name: 'Neymar Jr')
Player.find_or_create_by_id(id: 29, team_id: 6  ,name: 'Oscar')
Player.find_or_create_by_id(id: 30, team_id: 6  ,name: 'A Pato')
Player.find_or_create_by_id(id: 31, team_id: 29 ,name: 'Pedro')
Player.find_or_create_by_id(id: 32, team_id: 25 ,name: 'R van Persie')
Player.find_or_create_by_id(id: 33, team_id: 16 ,name: 'L Podolski')
Player.find_or_create_by_id(id: 36, team_id: 25 ,name: 'A Robben')
Player.find_or_create_by_id(id: 37, team_id: 9  ,name: 'J Rodriguez')
Player.find_or_create_by_id(id: 38, team_id: 27 ,name: 'C Ronaldo')
Player.find_or_create_by_id(id: 39, team_id: 14 ,name: 'W Rooney')
Player.find_or_create_by_id(id: 40, team_id: 8  ,name: 'A Sanchez')
Player.find_or_create_by_id(id: 41, team_id: 14 ,name: 'D Sturridge')
Player.find_or_create_by_id(id: 42, team_id: 31 ,name: 'L Suarez')
Player.find_or_create_by_id(id: 43, team_id: 29 ,name: 'F Torres')
Player.find_or_create_by_id(id: 44, team_id: 10 ,name: 'Y Toure')
Player.find_or_create_by_id(id: 45, team_id: 29 ,name: 'D Villa')
