Team.delete_all

Team.find_or_create_by_id(:id => 1,  :abbreviation => 'alg', :name => 'Algeria')
Team.find_or_create_by_id(:id => 2,  :abbreviation => 'arg', :name => 'Argentina')
Team.find_or_create_by_id(:id => 3,  :abbreviation => 'aus', :name => 'Australia')
Team.find_or_create_by_id(:id => 4,  :abbreviation => 'bel', :name => 'Belgium')
Team.find_or_create_by_id(:id => 5,  :abbreviation => 'bos', :name => 'Bosnia-Herzegovina')
Team.find_or_create_by_id(:id => 6,  :abbreviation => 'bra', :name => 'Brazil')
Team.find_or_create_by_id(:id => 7,  :abbreviation => 'cam', :name => 'Cameroon')
Team.find_or_create_by_id(:id => 8,  :abbreviation => 'chi', :name => 'Chile')
Team.find_or_create_by_id(:id => 9,  :abbreviation => 'col', :name => 'Colombia')
Team.find_or_create_by_id(:id => 10, :abbreviation => 'cot', :name => "Cote d'Ivoire")
Team.find_or_create_by_id(:id => 11, :abbreviation => 'cos', :name => 'Costa Rica')
Team.find_or_create_by_id(:id => 12, :abbreviation => 'cro', :name => 'Croatia')
Team.find_or_create_by_id(:id => 13, :abbreviation => 'ecu', :name => 'Ecuador')
Team.find_or_create_by_id(:id => 14, :abbreviation => 'eng', :name => 'England')
Team.find_or_create_by_id(:id => 15, :abbreviation => 'fra', :name => 'France')
Team.find_or_create_by_id(:id => 16, :abbreviation => 'ger', :name => 'Germany')
Team.find_or_create_by_id(:id => 17, :abbreviation => 'gha', :name => 'Ghana')
Team.find_or_create_by_id(:id => 18, :abbreviation => 'gre', :name => 'Greece')
Team.find_or_create_by_id(:id => 19, :abbreviation => 'hon', :name => 'Honduras')
Team.find_or_create_by_id(:id => 20, :abbreviation => 'ira', :name => 'Iran')
Team.find_or_create_by_id(:id => 21, :abbreviation => 'ita', :name => 'Italy')
Team.find_or_create_by_id(:id => 22, :abbreviation => 'jap', :name => 'Japan')
Team.find_or_create_by_id(:id => 23, :abbreviation => 'kor', :name => 'Korea Republic')
Team.find_or_create_by_id(:id => 24, :abbreviation => 'mex', :name => 'Mexico')
Team.find_or_create_by_id(:id => 25, :abbreviation => 'net', :name => 'Netherlands')
Team.find_or_create_by_id(:id => 26, :abbreviation => 'nig', :name => 'Nigeria')
Team.find_or_create_by_id(:id => 27, :abbreviation => 'por', :name => 'Portugal')
Team.find_or_create_by_id(:id => 28, :abbreviation => 'rus', :name => 'Russia')
Team.find_or_create_by_id(:id => 29, :abbreviation => 'spa', :name => 'Spain')
Team.find_or_create_by_id(:id => 30, :abbreviation => 'swi', :name => 'Switzerland')
Team.find_or_create_by_id(:id => 31, :abbreviation => 'uru', :name => 'Uruguay')
Team.find_or_create_by_id(:id => 32, :abbreviation => 'usa', :name => 'USA')

Team.find_or_create_by_id(:id => 33, :abbreviation => 'tba', :name => 'TBA')
