Team.delete_all

Team.create(id: 1,  abbreviation: 'arg', name: 'Argentina')
Team.create(id: 2,  abbreviation: 'aus', name: 'Australia')
Team.create(id: 3,  abbreviation: 'bel', name: 'Belgium')
Team.create(id: 4,  abbreviation: 'bra', name: 'Brazil')
Team.create(id: 5,  abbreviation: 'col', name: 'Colombia')
Team.create(id: 6,  abbreviation: 'cos', name: 'Costa Rica', short_name: 'Costa R.')
Team.create(id: 7,  abbreviation: 'cro', name: 'Croatia')
Team.create(id: 8,  abbreviation: 'den', name: 'Denmark')
Team.create(id: 9,  abbreviation: 'egy', name: 'Egypt')
Team.create(id: 10, abbreviation: 'eng', name: 'England')
Team.create(id: 11, abbreviation: 'fra', name: 'France')
Team.create(id: 12, abbreviation: 'ger', name: 'Germany')
Team.create(id: 13, abbreviation: 'ice', name: 'Iceland')
Team.create(id: 14, abbreviation: 'ira', name: 'Iran')
Team.create(id: 15, abbreviation: 'jap', name: 'Japan')
Team.create(id: 16, abbreviation: 'mex', name: 'Mexico')
Team.create(id: 17, abbreviation: 'mor', name: 'Morocco')
Team.create(id: 18, abbreviation: 'nig', name: 'Nigeria')
Team.create(id: 19, abbreviation: 'pan', name: 'Panama')
Team.create(id: 20, abbreviation: 'per', name: 'Peru')
Team.create(id: 21, abbreviation: 'pol', name: 'Poland')
Team.create(id: 22, abbreviation: 'por', name: 'Portugal')
Team.create(id: 23, abbreviation: 'rus', name: 'Russia')
Team.create(id: 24, abbreviation: 'sau', name: 'Saudi Arabia', short_name: 'Saudi A.')
Team.create(id: 25, abbreviation: 'sen', name: 'Senegal')
Team.create(id: 26, abbreviation: 'ser', name: 'Serbia')
Team.create(id: 27, abbreviation: 'kor', name: 'Korea Republic', short_name: 'Korea Rep.')
Team.create(id: 28, abbreviation: 'spa', name: 'Spain')
Team.create(id: 29, abbreviation: 'swe', name: 'Sweden')
Team.create(id: 30, abbreviation: 'swi', name: 'Switzerland', short_name: 'Swiss')
Team.create(id: 31, abbreviation: 'tun', name: 'Tunisia')
Team.create(id: 32, abbreviation: 'uru', name: 'Uruguay')

Team.create(id: 33, abbreviation: 'tba', name: 'TBA')
