Team.delete_all

Team.create(id: 1,  external_id: 762,  abbreviation: 'arg', name: 'Argentina')
Team.create(id: 2,  external_id: 779,  abbreviation: 'aus', name: 'Australia')
Team.create(id: 3,  external_id: 805,  abbreviation: 'bel', name: 'Belgium')
Team.create(id: 4,  external_id: 764,  abbreviation: 'bra', name: 'Brazil')
Team.create(id: 5,  external_id: 818,  abbreviation: 'col', name: 'Colombia')
Team.create(id: 6,  external_id: 793,  abbreviation: 'cos', name: 'Costa Rica', short_name: 'Costa R.')
Team.create(id: 7,  external_id: 799,  abbreviation: 'cro', name: 'Croatia')
Team.create(id: 8,  external_id: 782,  abbreviation: 'den', name: 'Denmark')
Team.create(id: 9,  external_id: 825,  abbreviation: 'egy', name: 'Egypt')
Team.create(id: 10, external_id: 770,  abbreviation: 'eng', name: 'England')
Team.create(id: 11, external_id: 773,  abbreviation: 'fra', name: 'France')
Team.create(id: 12, external_id: 759,  abbreviation: 'ger', name: 'Germany')
Team.create(id: 13, external_id: 1066, abbreviation: 'ice', name: 'Iceland')
Team.create(id: 14, external_id: 840,  abbreviation: 'ira', name: 'Iran')
Team.create(id: 15, external_id: 766,  abbreviation: 'jap', name: 'Japan')
Team.create(id: 16, external_id: 772,  abbreviation: 'kor', name: 'Korea Republic', short_name: 'Korea Rep.')
Team.create(id: 17, external_id: 769,  abbreviation: 'mex', name: 'Mexico')
Team.create(id: 18, external_id: 815,  abbreviation: 'mor', name: 'Morocco')
Team.create(id: 19, external_id: 776,  abbreviation: 'nig', name: 'Nigeria')
Team.create(id: 20, external_id: 1836, abbreviation: 'pan', name: 'Panama')
Team.create(id: 21, external_id: 832,  abbreviation: 'per', name: 'Peru')
Team.create(id: 22, external_id: 794,  abbreviation: 'pol', name: 'Poland')
Team.create(id: 23, external_id: 765,  abbreviation: 'por', name: 'Portugal')
Team.create(id: 24, external_id: 808,  abbreviation: 'rus', name: 'Russia')
Team.create(id: 25, external_id: 801,  abbreviation: 'sau', name: 'Saudi Arabia', short_name: 'Saudi A.')
Team.create(id: 26, external_id: 804,  abbreviation: 'sen', name: 'Senegal')
Team.create(id: 27, external_id: 780,  abbreviation: 'ser', name: 'Serbia')
Team.create(id: 28, external_id: 760,  abbreviation: 'spa', name: 'Spain')
Team.create(id: 29, external_id: 792,  abbreviation: 'swe', name: 'Sweden')
Team.create(id: 30, external_id: 788,  abbreviation: 'swi', name: 'Switzerland', short_name: 'Swiss')
Team.create(id: 31, external_id: 802,  abbreviation: 'tun', name: 'Tunisia')
Team.create(id: 32, external_id: 758,  abbreviation: 'uru', name: 'Uruguay')

Team.create(id: 33, abbreviation: 'tba', name: 'TBA')
