#Score.delete_all
#
#Score.find_or_create_by_id(:id => 1,  :fixture_id => 1,  :home => 1, :away => 3)
#Score.find_or_create_by_id(:id => 2,  :fixture_id => 2,  :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 3,  :fixture_id => 3,  :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 4,  :fixture_id => 4,  :home => 1, :away => 0)
#Score.find_or_create_by_id(:id => 5,  :fixture_id => 5,  :home => 4, :away => 0)
#Score.find_or_create_by_id(:id => 6,  :fixture_id => 6,  :home => 2, :away => 2)
#Score.find_or_create_by_id(:id => 7,  :fixture_id => 7,  :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 8,  :fixture_id => 8,  :home => 1, :away => 4)
#Score.find_or_create_by_id(:id => 9,  :fixture_id => 9,  :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 10, :fixture_id => 10, :home => 2, :away => 0)
#
#Score.find_or_create_by_id(:id => 131, :fixture_id => 131, :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 132, :fixture_id => 132, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 133, :fixture_id => 133, :home => 2, :away => 3)
#Score.find_or_create_by_id(:id => 134, :fixture_id => 134, :home => 0, :away => 0)
#Score.find_or_create_by_id(:id => 135, :fixture_id => 135, :home => 3, :away => 4)
#Score.find_or_create_by_id(:id => 136, :fixture_id => 136, :home => 3, :away => 0)
#Score.find_or_create_by_id(:id => 137, :fixture_id => 137, :home => 1, :away => 0)
#Score.find_or_create_by_id(:id => 138, :fixture_id => 138, :home => 5, :away => 1)
#Score.find_or_create_by_id(:id => 139, :fixture_id => 139, :home => 2, :away => 3)
#Score.find_or_create_by_id(:id => 140, :fixture_id => 140, :home => 1, :away => 2)
#
#Score.find_or_create_by_id(:id => 141, :fixture_id => 141, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 142, :fixture_id => 142, :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 143, :fixture_id => 143, :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 144, :fixture_id => 144, :home => 4, :away => 1)
#Score.find_or_create_by_id(:id => 145, :fixture_id => 145, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 146, :fixture_id => 146, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 147, :fixture_id => 147, :home => 3, :away => 2)
#Score.find_or_create_by_id(:id => 148, :fixture_id => 148, :home => 1, :away => 2)
#Score.find_or_create_by_id(:id => 149, :fixture_id => 149, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 150, :fixture_id => 150, :home => 0, :away => 2)
#
#Score.find_or_create_by_id(:id => 151, :fixture_id => 151, :home => 0, :away => 3)
#Score.find_or_create_by_id(:id => 152, :fixture_id => 152, :home => 1, :away => 0)
#Score.find_or_create_by_id(:id => 153, :fixture_id => 153, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 154, :fixture_id => 154, :home => 4, :away => 1)
#Score.find_or_create_by_id(:id => 155, :fixture_id => 155, :home => 0, :away => 0)
#Score.find_or_create_by_id(:id => 156, :fixture_id => 156, :home => 6, :away => 3)
#Score.find_or_create_by_id(:id => 157, :fixture_id => 157, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 158, :fixture_id => 158, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 159, :fixture_id => 159, :home => 0, :away => 5)
#Score.find_or_create_by_id(:id => 160, :fixture_id => 160, :home => 0, :away => 0)
#
#Score.find_or_create_by_id(:id => 161, :fixture_id => 161, :home => 0, :away => 0)
#Score.find_or_create_by_id(:id => 162, :fixture_id => 162, :home => 0, :away => 3)
#Score.find_or_create_by_id(:id => 163, :fixture_id => 163, :home => 2, :away => 4)
#Score.find_or_create_by_id(:id => 164, :fixture_id => 164, :home => 3, :away => 1)
#Score.find_or_create_by_id(:id => 165, :fixture_id => 165, :home => 3, :away => 1)
#Score.find_or_create_by_id(:id => 166, :fixture_id => 166, :home => 2, :away => 3)
#Score.find_or_create_by_id(:id => 167, :fixture_id => 167, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 168, :fixture_id => 168, :home => 0, :away => 0)
#Score.find_or_create_by_id(:id => 169, :fixture_id => 169, :home => 1, :away => 2)
#Score.find_or_create_by_id(:id => 170, :fixture_id => 170, :home => 1, :away => 1)
#
#Score.find_or_create_by_id(:id => 171, :fixture_id => 171, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 172, :fixture_id => 172, :home => 0, :away => 3)
#Score.find_or_create_by_id(:id => 173, :fixture_id => 173, :home => 1, :away => 0)
#Score.find_or_create_by_id(:id => 174, :fixture_id => 174, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 175, :fixture_id => 175, :home => 2, :away => 3)
#Score.find_or_create_by_id(:id => 176, :fixture_id => 176, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 177, :fixture_id => 177, :home => 5, :away => 1)
#Score.find_or_create_by_id(:id => 178, :fixture_id => 178, :home => 1, :away => 2)
#Score.find_or_create_by_id(:id => 179, :fixture_id => 179, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 180, :fixture_id => 180, :home => 1, :away => 3)
#
#Score.find_or_create_by_id(:id => 181, :fixture_id => 181, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 182, :fixture_id => 182, :home => 2, :away => 2)
#Score.find_or_create_by_id(:id => 183, :fixture_id => 183, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 184, :fixture_id => 184, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 185, :fixture_id => 185, :home => 6, :away => 0)
#Score.find_or_create_by_id(:id => 186, :fixture_id => 186, :home => 1, :away => 0)
#Score.find_or_create_by_id(:id => 187, :fixture_id => 187, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 188, :fixture_id => 188, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 189, :fixture_id => 189, :home => 3, :away => 0)
#Score.find_or_create_by_id(:id => 190, :fixture_id => 190, :home => 3, :away => 3)
#
#Score.find_or_create_by_id(:id => 901, :fixture_id => 191, :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 902, :fixture_id => 192, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 903, :fixture_id => 193, :home => 2, :away => 1)
#Score.find_or_create_by_id(:id => 904, :fixture_id => 194, :home => 2, :away => 0)
#Score.find_or_create_by_id(:id => 905, :fixture_id => 195, :home => 1, :away => 2)
#Score.find_or_create_by_id(:id => 906, :fixture_id => 196, :home => 0, :away => 3)
#Score.find_or_create_by_id(:id => 907, :fixture_id => 197, :home => 1, :away => 1)
#Score.find_or_create_by_id(:id => 908, :fixture_id => 198, :home => 0, :away => 1)
#Score.find_or_create_by_id(:id => 909, :fixture_id => 199, :home => 2, :away => 3)
#Score.find_or_create_by_id(:id => 910, :fixture_id => 200, :home => 1, :away => 0)