Team.delete_all

Team.find_or_create_by_id(id: 1,  external_id: 0,  abbreviation: 'aut', name: 'Austria')
Team.find_or_create_by_id(id: 2,  external_id: 0,  abbreviation: 'bel', name: 'Belgium')
Team.find_or_create_by_id(id: 3,  external_id: 0,  abbreviation: 'cro', name: 'Croatia')
Team.find_or_create_by_id(id: 4,  external_id: 0,  abbreviation: 'cze', name: 'Czech Rep.')
Team.find_or_create_by_id(id: 5,  external_id: 0,  abbreviation: 'den', name: 'Denmark')
Team.find_or_create_by_id(id: 6,  external_id: 0,  abbreviation: 'eng', name: 'England')
Team.find_or_create_by_id(id: 7,  external_id: 0,  abbreviation: 'fin', name: 'Finland')
Team.find_or_create_by_id(id: 8,  external_id: 0,  abbreviation: 'fra', name: 'France')
Team.find_or_create_by_id(id: 9,  external_id: 0,  abbreviation: 'ger', name: 'Germany')
Team.find_or_create_by_id(id: 10, external_id: 0,  abbreviation: 'hun', name: 'Hungary')
Team.find_or_create_by_id(id: 11, external_id: 0,  abbreviation: 'ita', name: 'Italy')
Team.find_or_create_by_id(id: 12, external_id: 0,  abbreviation: 'net', name: 'Netherlands')
Team.find_or_create_by_id(id: 13, external_id: 0,  abbreviation: 'nma', name: 'N. Macedonia')
Team.find_or_create_by_id(id: 14, external_id: 0,  abbreviation: 'pol', name: 'Poland')
Team.find_or_create_by_id(id: 15, external_id: 0,  abbreviation: 'por', name: 'Portugal')
Team.find_or_create_by_id(id: 16, external_id: 0,  abbreviation: 'rus', name: 'Russia')
Team.find_or_create_by_id(id: 17, external_id: 0,  abbreviation: 'sco', name: 'Scotland')
Team.find_or_create_by_id(id: 18, external_id: 0,  abbreviation: 'slo', name: 'Slovakia')
Team.find_or_create_by_id(id: 19, external_id: 0,  abbreviation: 'spa', name: 'Spain')
Team.find_or_create_by_id(id: 20, external_id: 0,  abbreviation: 'swe', name: 'Sweden')
Team.find_or_create_by_id(id: 21, external_id: 0,  abbreviation: 'swi', name: 'Switzerland')
Team.find_or_create_by_id(id: 22, external_id: 0,  abbreviation: 'tur', name: 'Turkey')
Team.find_or_create_by_id(id: 23, external_id: 0,  abbreviation: 'ukr', name: 'Ukraine')
Team.find_or_create_by_id(id: 24, external_id: 0,  abbreviation: 'wal', name: 'Wales')

Team.find_or_create_by_id(id: 25, abbreviation: 'tba', name: 'TBA')
