Team.delete_all

Team.create(id: 1,  external_id: 3942312, abbreviation: 'aut', name: 'Austria')
Team.create(id: 2,  external_id: 8263,    abbreviation: 'bel', name: 'Belgium')
Team.create(id: 3,  external_id: 10155,   abbreviation: 'cro', name: 'Croatia')
Team.create(id: 4,  external_id: 8496,    abbreviation: 'cze', name: 'Czech Rep.')
Team.create(id: 5,  external_id: 5818,    abbreviation: 'den', name: 'Denmark')
Team.create(id: 6,  external_id: 5811,    abbreviation: 'eng', name: 'England')
Team.create(id: 7,  external_id: 7871,    abbreviation: 'fin', name: 'Finland')
Team.create(id: 8,  external_id: 6723,    abbreviation: 'fra', name: 'France')
Team.create(id: 9,  external_id: 8570,    abbreviation: 'ger', name: 'Germany')
Team.create(id: 10, external_id: 8565,    abbreviation: 'hun', name: 'Hungary')
Team.create(id: 11, external_id: 8204,    abbreviation: 'ita', name: 'Italy')
Team.create(id: 12, external_id: 6708,    abbreviation: 'net', name: 'Netherlands')
Team.create(id: 13, external_id: 8260,    abbreviation: 'nma', name: 'N. Macedonia')
Team.create(id: 14, external_id: 8568,    abbreviation: 'pol', name: 'Poland')
Team.create(id: 15, external_id: 8361,    abbreviation: 'por', name: 'Portugal')
Team.create(id: 16, external_id: 5817,    abbreviation: 'rus', name: 'Russia')
Team.create(id: 17, external_id: 8498,    abbreviation: 'sco', name: 'Scotland')
Team.create(id: 18, external_id: 8497,    abbreviation: 'svk', name: 'Slovakia')
Team.create(id: 19, external_id: 6720,    abbreviation: 'spa', name: 'Spain')
Team.create(id: 20, external_id: 8520,    abbreviation: 'swe', name: 'Sweden')
Team.create(id: 21, external_id: 6717,    abbreviation: 'swi', name: 'Switzerland')
Team.create(id: 22, external_id: 6595,    abbreviation: 'tur', name: 'Turkey')
Team.create(id: 23, external_id: 6718,    abbreviation: 'ukr', name: 'Ukraine')
Team.create(id: 24, external_id: 5790,    abbreviation: 'wal', name: 'Wales')

Team.create(id: 25, abbreviation: 'tba', name: 'TBA')
