Team.delete_all

Team.find_or_create_by_id(id: 1,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 2,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 3,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 4,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 5,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 6,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 7,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 8,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 9,  abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 10, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 11, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 12, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 13, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 14, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 15, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 16, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 17, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 18, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 19, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 20, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 21, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 22, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 23, abbreviation: '', name: '', external_id: nil)
Team.find_or_create_by_id(id: 24, abbreviation: '', name: '', external_id: nil)

Team.find_or_create_by_id(id: 25, abbreviation: 'tba', name: 'TBA')
