defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: developer
  password: password
  port: 15432
  pool: 5

development:
  <<: *defaults
  database: footy_development

test: &test
  <<: *defaults
  database: footy_test

production:
  <<: *defaults
  database: footy_production
  username: hidden
  password: hidden
  port: 5432
