defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: <%= ENV['DB_USR'] %>
  password: <%= ENV['DB_PWD'] %>
  port: 5432
  pool: 5

development:
  <<: *defaults
  database: footy_development

test: &test
  <<: *defaults
  database: footy_test

production:
  <<: *defaults
  database: footy_production
  port: 5432
