defaults: &defaults
  round_open_period_in_days: 3
#  competition: premier_league
#  knockout_rounds: []
  competition: world_cup
  knockout_rounds: [4,5,6,7]
  teams_in: ['arg','bra', 'ger','net']

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
