defaults: &defaults
  round_open_period_in_days: 7
#  competition: premier_league
#  knockout_rounds: []
  competition: world_cup
  knockout_rounds: [4,5,6,7]
  teams_in: ['alg','arg','bel','bra','col','cos','fra','ger','gre','mex','net','nig','swi','usa']

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
