defaults: &defaults
  round_open_period_in_days: 7
  days_in_advance_to_sync_fixtures: 8
  competition: premier_league
  week_jackpot:
  premier_league:
    type: club
    knockout_rounds: []
  world_cup:
    type: international
    knockout_rounds: [4,5,6,7]
  america_cup:
    type: international
    knockout_rounds: [4,5,6]
  euro_cup:
    type: international
    knockout_rounds: []
  confederations_cup:
    type: international
    knockout_rounds: []
  club:
    strip_path: 'club/strip/'
    badge_path: 'club/badge/'
  international:
    strip_path: 'international/flag/'
    badge_path: 'international/flag/'
  feed:
    football_data_api:
      url: http://api.football-data.org
      competition_id: 445
    football_api:
      url: http://api.football-api.com/2.0/
      competition_id: 1204
    e_api:
      url: placeholder
      competition_id: 47
  bonus_threshold: 20
  bonus_amount: 10
  bonus_points_matrix: 30
  bonus_weeks: [19]

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults