defaults: &defaults
  round_open_period_in_days: 4
  competition: copa_cup
  premier_league:
    knockout_rounds: []
  world_cup:
    knockout_rounds: [4,5,6,7]
    teams_in: ['arg','bra', 'ger','net']
  copa_cup:
    knockout_rounds: [4,5,6]
    teams_in: []
  days_in_advance_to_sync_fixtures: 7
  feed:
    url: http://football-api.com/api/
    competition_id: 1204
  mixpanel_token: '16027af902901654dd96dd7eab86b899'

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults