defaults: &defaults
  round_open_period_in_days: 7
#  competition: premier_league
#  knockout_rounds: []
  competition: world_cup
  knockout_rounds: [4,5,6,7]

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
