defaults: &defaults
  round_open_period_in_days: 7
  days_in_advance_to_sync_fixtures: 8
  competition: premier_league
  premier_league:
    type: club
    knockout_rounds: []
  world_cup:
    type: international
    knockout_rounds: [4,5,6,7]
  america_cup:
    type: international
    knockout_rounds: [4,5,6]
  club:
    strip_path: 'club/strip/'
    badge_path: 'club/badge/'
  international:
    strip_path: 'international/flag/'
    badge_path: 'international/flag/'
  feed:
    url: http://football-api.com/api/
    competition_id: 1204
  mixpanel_token: '16027af902901654dd96dd7eab86b899'

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults