defaults: &defaults
  round_open_period_in_days: 4
  days_in_advance_to_sync_fixtures: 8
  competition: euro_cup
  premier_league:
    type: club
    knockout_rounds: []
  world_cup:
    type: international
    knockout_rounds: [4,5,6,7]
  america_cup:
    type: international
    knockout_rounds: [4,5,6]
  euro_cup:
    type: international
    knockout_rounds: []
  club:
    strip_path: 'club/strip/'
    badge_path: 'club/badge/'
  international:
    strip_path: 'international/flag/'
    badge_path: 'international/flag/'
  feed:
    football_data_api:
      url: http://api.football-data.org
      competition_id: 424 #398
    football_api:
      url: http://football-api.com/api/
      competition_id: 1204

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults