defaults: &defaults
  round_open_period_in_days: 7
  competition: premier_league
  knockout_rounds: []
#  competition: world_cup
#  knockout_rounds: [4,5,6,7]
#  teams_in: ['arg','bra', 'ger','net']
  days_in_advance_to_sync_fixtures: 7
  feed:
    url: http://football-api.com/api/?Action=fixtures
    api_key: 23874509-922b-abe2-847ab13dadba
    competition_id: 1204
  toggles:
    sms_communications: true

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
  toggles:
    sms_communications: false
