defaults: &defaults
  sms_communications: true
  last_man_standing: false
  five_alive: true
  bet_type_hda: false

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults