defaults: &defaults
  bet_type_hda: true
  last_man_standing: true
  goal_buster: false
  five_alive: false
  sweep: false
  week_deadline: false
  sms_communications: true
#  feed: football_api
  feed: football_data_api

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
