defaults: &defaults
  bet_type_hda: true
  last_man_standing: false
  goal_buster: false
  five_alive: true
  sweep: true
  week_deadline: false
  sms_communications: true
#  feed: football_api
  feed: football_data_api

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
