defaults: &defaults
  bet_type_hda: true
  last_man_standing: false
  goal_buster: false
  five_alive: false
  five_alive_twist: false
  sweep: false
  week_deadline: false
  sms_communications: false
  bonus_points: true
  feed: e_api
  form_for_bets: true
  analytics: false
  log_web_requests: false

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
