defaults: &defaults
  sms_communications: true
  last_man_standing: true
  five_alive: false
  bet_type_hda: true
  week_deadline: false

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
