defaults: &defaults
  bet_type_hda: true
  last_man_standing: false
  goal_buster: false
  five_alive: true
  five_alive_twist: false
  sweep: true
  week_deadline: false
  sms_communications: false
  bonus_points: false
  feed: football_api
  form_for_bets: false

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
