Fixture.delete_all

Fixture.create(id: 1,   name: 'BRI-CHE', week_id: 1)
Fixture.create(id: 2,   name: 'BUR-MUN', week_id: 1)
Fixture.create(id: 3,   name: 'CRY-SOU', week_id: 1)
Fixture.create(id: 4,   name: 'FUL-ARS', week_id: 1)
Fixture.create(id: 5,   name: 'LIV-LEE', week_id: 1)
Fixture.create(id: 6,   name: 'MCI-AST', week_id: 1)
Fixture.create(id: 7,   name: 'SHU-WOL', week_id: 1)
Fixture.create(id: 8,   name: 'TOT-EVE', week_id: 1)
Fixture.create(id: 9,   name: 'WBR-LEI', week_id: 1)
Fixture.create(id: 10,  name: 'WHA-NEW', week_id: 1)

Fixture.create(id: 11,  name: 'ARS-WHA', week_id: 2)
Fixture.create(id: 12,  name: 'AST-SHU', week_id: 2)
Fixture.create(id: 13,  name: 'CHE-LIV', week_id: 2)
Fixture.create(id: 14,  name: 'EVE-WBR', week_id: 2)
Fixture.create(id: 15,  name: 'LEE-FUL', week_id: 2)
Fixture.create(id: 16,  name: 'LEI-BUR', week_id: 2)
Fixture.create(id: 17,  name: 'MUN-CRY', week_id: 2)
Fixture.create(id: 18,  name: 'NEW-BRI', week_id: 2)
Fixture.create(id: 19,  name: 'SOU-TOT', week_id: 2)
Fixture.create(id: 20,  name: 'WOL-MCI', week_id: 2)

Fixture.create(id: 21,  name: 'BRI-MUN', week_id: 3)
Fixture.create(id: 22,  name: 'BUR-SOU', week_id: 3)
Fixture.create(id: 23,  name: 'CRY-EVE', week_id: 3)
Fixture.create(id: 24,  name: 'FUL-AST', week_id: 3)
Fixture.create(id: 25,  name: 'LIV-ARS', week_id: 3)
Fixture.create(id: 26,  name: 'MCI-LEI', week_id: 3)
Fixture.create(id: 27,  name: 'TOT-NEW', week_id: 3)
Fixture.create(id: 28,  name: 'SHU-LEE', week_id: 3)
Fixture.create(id: 29,  name: 'WBR-CHE', week_id: 3)
Fixture.create(id: 30,  name: 'WHA-WOL', week_id: 3)

Fixture.create(id: 31,  name: 'ARS-SHU', week_id: 4)
Fixture.create(id: 32,  name: 'AST-LIV', week_id: 4)
Fixture.create(id: 33,  name: 'CHE-CRY', week_id: 4)
Fixture.create(id: 34,  name: 'EVE-BRI', week_id: 4)
Fixture.create(id: 35,  name: 'LEE-MCI', week_id: 4)
Fixture.create(id: 36,  name: 'LEI-WHA', week_id: 4)
Fixture.create(id: 37,  name: 'MUN-TOT', week_id: 4)
Fixture.create(id: 38,  name: 'NEW-BUR', week_id: 4)
Fixture.create(id: 39,  name: 'SOU-WBR', week_id: 4)
Fixture.create(id: 40,  name: 'WOL-FUL', week_id: 4)

Fixture.create(id: 41,  name: 'CHE-SOU', week_id: 5)
Fixture.create(id: 42,  name: 'CRY-BRI', week_id: 5)
Fixture.create(id: 43,  name: 'EVE-LIV', week_id: 5)
Fixture.create(id: 44,  name: 'LEE-WOL', week_id: 5)
Fixture.create(id: 45,  name: 'LEI-AST', week_id: 5)
Fixture.create(id: 46,  name: 'MCI-ARS', week_id: 5)
Fixture.create(id: 47,  name: 'NEW-MUN', week_id: 5)
Fixture.create(id: 48,  name: 'SHU-FUL', week_id: 5)
Fixture.create(id: 49,  name: 'TOT-WHA', week_id: 5)
Fixture.create(id: 50,  name: 'WBR-BUR', week_id: 5)

Fixture.create(id: 51,  name: 'ARS-LEI', week_id: 6)
Fixture.create(id: 52,  name: 'AST-LEE', week_id: 6)
Fixture.create(id: 53,  name: 'BRI-WBR', week_id: 6)
Fixture.create(id: 54,  name: 'BUR-TOT', week_id: 6)
Fixture.create(id: 55,  name: 'FUL-CRY', week_id: 6)
Fixture.create(id: 56,  name: 'LIV-SHU', week_id: 6)
Fixture.create(id: 57,  name: 'MUN-CHE', week_id: 6)
Fixture.create(id: 58,  name: 'SOU-EVE', week_id: 6)
Fixture.create(id: 59,  name: 'WHA-MCI', week_id: 6)
Fixture.create(id: 60,  name: 'WOL-NEW', week_id: 6)

Fixture.create(id: 61,  name: 'AST-SOU', week_id: 7)
Fixture.create(id: 62,  name: 'BUR-CHE', week_id: 7)
Fixture.create(id: 63,  name: 'FUL-WBR', week_id: 7)
Fixture.create(id: 64,  name: 'LEE-LEI', week_id: 7)
Fixture.create(id: 65,  name: 'LIV-WHA', week_id: 7)
Fixture.create(id: 66,  name: 'MUN-ARS', week_id: 7)
Fixture.create(id: 67,  name: 'NEW-EVE', week_id: 7)
Fixture.create(id: 68,  name: 'SHU-MCI', week_id: 7)
Fixture.create(id: 69,  name: 'TOT-BRI', week_id: 7)
Fixture.create(id: 70,  name: 'WOL-CRY', week_id: 7)

Fixture.create(id: 71,  name: 'ARS-AST', week_id: 8)
Fixture.create(id: 72,  name: 'BRI-BUR', week_id: 8)
Fixture.create(id: 73,  name: 'CHE-SHU', week_id: 8)
Fixture.create(id: 74,  name: 'CRY-LEE', week_id: 8)
Fixture.create(id: 75,  name: 'EVE-MUN', week_id: 8)
Fixture.create(id: 76,  name: 'LEI-WOL', week_id: 8)
Fixture.create(id: 77,  name: 'MCI-LIV', week_id: 8)
Fixture.create(id: 78,  name: 'SOU-NEW', week_id: 8)
Fixture.create(id: 79,  name: 'WBR-TOT', week_id: 8)
Fixture.create(id: 80,  name: 'WHA-FUL', week_id: 8)

Fixture.create(id: 81,  name: 'AST-BRI', week_id: 9)
Fixture.create(id: 82,  name: 'BUR-CRY', week_id: 9)
Fixture.create(id: 83,  name: 'FUL-EVE', week_id: 9)
Fixture.create(id: 84,  name: 'LEE-ARS', week_id: 9)
Fixture.create(id: 85,  name: 'LIV-LEI', week_id: 9)
Fixture.create(id: 86,  name: 'MUN-WBR', week_id: 9)
Fixture.create(id: 87,  name: 'NEW-CHE', week_id: 9)
Fixture.create(id: 88,  name: 'SHU-WHA', week_id: 9)
Fixture.create(id: 89,  name: 'TOT-MCI', week_id: 9)
Fixture.create(id: 90,  name: 'WOL-SOU', week_id: 9)

Fixture.create(id: 91,  name: 'ARS-WOL', week_id: 10)
Fixture.create(id: 92,  name: 'BRI-LIV', week_id: 10)
Fixture.create(id: 93,  name: 'CHE-TOT', week_id: 10)
Fixture.create(id: 94,  name: 'CRY-NEW', week_id: 10)
Fixture.create(id: 95,  name: 'EVE-LEE', week_id: 10)
Fixture.create(id: 96,  name: 'LEI-FUL', week_id: 10)
Fixture.create(id: 97,  name: 'MCI-BUR', week_id: 10)
Fixture.create(id: 98,  name: 'SOU-MUN', week_id: 10)
Fixture.create(id: 99,  name: 'WBR-SHU', week_id: 10)
Fixture.create(id: 100, name: 'WHA-AST', week_id: 10)

Fixture.create(id: 101, name: 'AST-NEW', week_id: 11)
Fixture.create(id: 102, name: 'BRI-SOU', week_id: 11)
Fixture.create(id: 103, name: 'BUR-EVE', week_id: 11)
Fixture.create(id: 104, name: 'CHE-LEE', week_id: 11)
Fixture.create(id: 105, name: 'LIV-WOL', week_id: 11)
Fixture.create(id: 106, name: 'MCI-FUL', week_id: 11)
Fixture.create(id: 107, name: 'SHU-LEI', week_id: 11)
Fixture.create(id: 108, name: 'TOT-ARS', week_id: 11)
Fixture.create(id: 109, name: 'WBR-CRY', week_id: 11)
Fixture.create(id: 110, name: 'WHA-MUN', week_id: 11)

Fixture.create(id: 111, name: 'ARS-BUR', week_id: 12)
Fixture.create(id: 112, name: 'CRY-TOT', week_id: 12)
Fixture.create(id: 113, name: 'EVE-CHE', week_id: 12)
Fixture.create(id: 114, name: 'FUL-LIV', week_id: 12)
Fixture.create(id: 115, name: 'LEE-WHA', week_id: 12)
Fixture.create(id: 116, name: 'LEI-BRI', week_id: 12)
Fixture.create(id: 117, name: 'MUN-MCI', week_id: 12)
Fixture.create(id: 118, name: 'NEW-WBR', week_id: 12)
Fixture.create(id: 119, name: 'SOU-SHU', week_id: 12)
Fixture.create(id: 120, name: 'WOL-AST', week_id: 12)

Fixture.create(id: 121, name: 'ARS-SOU', week_id: 13)
Fixture.create(id: 122, name: 'AST-BUR', week_id: 13)
Fixture.create(id: 123, name: 'FUL-BRI', week_id: 13)
Fixture.create(id: 124, name: 'LEE-NEW', week_id: 13)
Fixture.create(id: 125, name: 'LEI-EVE', week_id: 13)
Fixture.create(id: 126, name: 'LIV-TOT', week_id: 13)
Fixture.create(id: 127, name: 'MCI-WBR', week_id: 13)
Fixture.create(id: 128, name: 'SHU-MUN', week_id: 13)
Fixture.create(id: 129, name: 'WOL-CHE', week_id: 13)
Fixture.create(id: 130, name: 'WHA-CRY', week_id: 13)

Fixture.create(id: 131, name: 'BRI-SHU', week_id: 14)
Fixture.create(id: 132, name: 'BUR-WOL', week_id: 14)
Fixture.create(id: 133, name: 'CHE-WHA', week_id: 14)
Fixture.create(id: 134, name: 'CRY-LIV', week_id: 14)
Fixture.create(id: 135, name: 'EVE-ARS', week_id: 14)
Fixture.create(id: 136, name: 'MUN-LEE', week_id: 14)
Fixture.create(id: 137, name: 'NEW-FUL', week_id: 14)
Fixture.create(id: 138, name: 'SOU-MCI', week_id: 14)
Fixture.create(id: 139, name: 'TOT-LEI', week_id: 14)
Fixture.create(id: 140, name: 'WBR-AST', week_id: 14)

Fixture.create(id: 141, name: 'ARS-CHE', week_id: 15)
Fixture.create(id: 142, name: 'AST-CRY', week_id: 15)
Fixture.create(id: 143, name: 'FUL-SOU', week_id: 15)
Fixture.create(id: 144, name: 'LEE-BUR', week_id: 15)
Fixture.create(id: 145, name: 'LEI-MUN', week_id: 15)
Fixture.create(id: 146, name: 'LIV-WBR', week_id: 15)
Fixture.create(id: 147, name: 'MCI-NEW', week_id: 15)
Fixture.create(id: 148, name: 'SHU-EVE', week_id: 15)
Fixture.create(id: 149, name: 'WOL-TOT', week_id: 15)
Fixture.create(id: 150, name: 'WHA-BRI', week_id: 15)

Fixture.create(id: 151, name: 'BRI-ARS', week_id: 16)
Fixture.create(id: 152, name: 'BUR-SHU', week_id: 16)
Fixture.create(id: 153, name: 'CHE-AST', week_id: 16)
Fixture.create(id: 154, name: 'CRY-LEI', week_id: 16)
Fixture.create(id: 160, name: 'EVE-MCI', week_id: 16)
Fixture.create(id: 155, name: 'MUN-WOL', week_id: 16)
Fixture.create(id: 156, name: 'NEW-LIV', week_id: 16)
Fixture.create(id: 157, name: 'SOU-WHA', week_id: 16)
Fixture.create(id: 158, name: 'TOT-FUL', week_id: 16)
Fixture.create(id: 159, name: 'WBR-LEE', week_id: 16)

Fixture.create(id: 161, name: '', week_id: 17)
Fixture.create(id: 162, name: '', week_id: 17)
Fixture.create(id: 163, name: '', week_id: 17)
Fixture.create(id: 164, name: '', week_id: 17)
Fixture.create(id: 165, name: '', week_id: 17)
Fixture.create(id: 166, name: '', week_id: 17)
Fixture.create(id: 167, name: '', week_id: 17)
Fixture.create(id: 168, name: '', week_id: 17)
Fixture.create(id: 169, name: '', week_id: 17)
Fixture.create(id: 170, name: '', week_id: 17)

# Fixture.create(id: 171, name: '', week_id: 18)
# Fixture.create(id: 172, name: '', week_id: 18)
# Fixture.create(id: 173, name: '', week_id: 18)
# Fixture.create(id: 174, name: '', week_id: 18)
# Fixture.create(id: 175, name: '', week_id: 18)
# Fixture.create(id: 176, name: '', week_id: 18)
# Fixture.create(id: 177, name: '', week_id: 18)
# Fixture.create(id: 178, name: '', week_id: 18)
# Fixture.create(id: 179, name: '', week_id: 18)
# Fixture.create(id: 180, name: '', week_id: 18)
#
# Fixture.create(id: 181, name: '', week_id: 19)
# Fixture.create(id: 182, name: '', week_id: 19)
# Fixture.create(id: 183, name: '', week_id: 19)
# Fixture.create(id: 184, name: '', week_id: 19)
# Fixture.create(id: 185, name: '', week_id: 19)
# Fixture.create(id: 186, name: '', week_id: 19)
# Fixture.create(id: 187, name: '', week_id: 19)
# Fixture.create(id: 188, name: '', week_id: 19)
# Fixture.create(id: 189, name: '', week_id: 19)
# Fixture.create(id: 190, name: '', week_id: 19)
#
# Fixture.create(id: 191, name: '', week_id: 20)
# Fixture.create(id: 192, name: '', week_id: 20)
# Fixture.create(id: 193, name: '', week_id: 20)
# Fixture.create(id: 194, name: '', week_id: 20)
# Fixture.create(id: 195, name: '', week_id: 20)
# Fixture.create(id: 196, name: '', week_id: 20)
# Fixture.create(id: 197, name: '', week_id: 20)
# Fixture.create(id: 198, name: '', week_id: 20)
# Fixture.create(id: 199, name: '', week_id: 20)
# Fixture.create(id: 200, name: '', week_id: 20)
#
# Fixture.create(id: 201, name: '', week_id: 21)
# Fixture.create(id: 202, name: '', week_id: 21)
# Fixture.create(id: 203, name: '', week_id: 21)
# Fixture.create(id: 204, name: '', week_id: 21)
# Fixture.create(id: 205, name: '', week_id: 21)
# Fixture.create(id: 206, name: '', week_id: 21)
# Fixture.create(id: 207, name: '', week_id: 21)
# Fixture.create(id: 208, name: '', week_id: 21)
# Fixture.create(id: 209, name: '', week_id: 21)
# Fixture.create(id: 210, name: '', week_id: 21)
#
# Fixture.create(id: 211, name: '', week_id: 22)
# Fixture.create(id: 212, name: '', week_id: 22)
# Fixture.create(id: 213, name: '', week_id: 22)
# Fixture.create(id: 214, name: '', week_id: 22)
# Fixture.create(id: 215, name: '', week_id: 22)
# Fixture.create(id: 216, name: '', week_id: 22)
# Fixture.create(id: 217, name: '', week_id: 22)
# Fixture.create(id: 218, name: '', week_id: 22)
# Fixture.create(id: 219, name: '', week_id: 22)
# Fixture.create(id: 220, name: '', week_id: 22)
#
# Fixture.create(id: 221, name: '', week_id: 23)
# Fixture.create(id: 222, name: '', week_id: 23)
# Fixture.create(id: 223, name: '', week_id: 23)
# Fixture.create(id: 224, name: '', week_id: 23)
# Fixture.create(id: 225, name: '', week_id: 23)
# Fixture.create(id: 226, name: '', week_id: 23)
# Fixture.create(id: 227, name: '', week_id: 23)
# Fixture.create(id: 228, name: '', week_id: 23)
# Fixture.create(id: 229, name: '', week_id: 23)
# Fixture.create(id: 230, name: '', week_id: 23)
#
# Fixture.create(id: 231, name: '', week_id: 24)
# Fixture.create(id: 232, name: '', week_id: 24)
# Fixture.create(id: 233, name: '', week_id: 24)
# Fixture.create(id: 234, name: '', week_id: 24)
# Fixture.create(id: 235, name: '', week_id: 24)
# Fixture.create(id: 236, name: '', week_id: 24)
# Fixture.create(id: 237, name: '', week_id: 24)
# Fixture.create(id: 238, name: '', week_id: 24)
# Fixture.create(id: 239, name: '', week_id: 24)
# Fixture.create(id: 240, name: '', week_id: 24)
#
# Fixture.create(id: 241, name: '', week_id: 25)
# Fixture.create(id: 242, name: '', week_id: 25)
# Fixture.create(id: 243, name: '', week_id: 25)
# Fixture.create(id: 244, name: '', week_id: 25)
# Fixture.create(id: 245, name: '', week_id: 25)
# Fixture.create(id: 246, name: '', week_id: 25)
# Fixture.create(id: 247, name: '', week_id: 25)
# Fixture.create(id: 248, name: '', week_id: 25)
# Fixture.create(id: 249, name: '', week_id: 25)
# Fixture.create(id: 250, name: '', week_id: 25)
#
# Fixture.create(id: 251, name: '', week_id: 26)
# Fixture.create(id: 252, name: '', week_id: 26)
# Fixture.create(id: 253, name: '', week_id: 26)
# Fixture.create(id: 254, name: '', week_id: 26)
# Fixture.create(id: 255, name: '', week_id: 26)
# Fixture.create(id: 256, name: '', week_id: 26)
# Fixture.create(id: 257, name: '', week_id: 26)
# Fixture.create(id: 258, name: '', week_id: 26)
# Fixture.create(id: 259, name: '', week_id: 26)
# Fixture.create(id: 260, name: '', week_id: 26)
#
# Fixture.create(id: 261, name: '', week_id: 27)
# Fixture.create(id: 262, name: '', week_id: 27)
# Fixture.create(id: 263, name: '', week_id: 27)
# Fixture.create(id: 264, name: '', week_id: 27)
# Fixture.create(id: 265, name: '', week_id: 27)
# Fixture.create(id: 266, name: '', week_id: 27)
# Fixture.create(id: 267, name: '', week_id: 27)
# Fixture.create(id: 268, name: '', week_id: 27)
# Fixture.create(id: 269, name: '', week_id: 27)
# Fixture.create(id: 270, name: '', week_id: 27)
#
# Fixture.create(id: 271, name: '', week_id: 28)
# Fixture.create(id: 272, name: '', week_id: 28)
# Fixture.create(id: 273, name: '', week_id: 28)
# Fixture.create(id: 274, name: '', week_id: 28)
# Fixture.create(id: 275, name: '', week_id: 28)
# Fixture.create(id: 276, name: '', week_id: 28)
# Fixture.create(id: 277, name: '', week_id: 28)
# Fixture.create(id: 278, name: '', week_id: 28)
# Fixture.create(id: 279, name: '', week_id: 28)
# Fixture.create(id: 280, name: '', week_id: 28)
#
# Fixture.create(id: 281, name: '', week_id: 29)
# Fixture.create(id: 282, name: '', week_id: 29)
# Fixture.create(id: 283, name: '', week_id: 29)
# Fixture.create(id: 284, name: '', week_id: 29)
# Fixture.create(id: 285, name: '', week_id: 29)
# Fixture.create(id: 286, name: '', week_id: 29)
# Fixture.create(id: 287, name: '', week_id: 29)
# Fixture.create(id: 288, name: '', week_id: 29)
# Fixture.create(id: 289, name: '', week_id: 29)
# Fixture.create(id: 290, name: '', week_id: 29)
#
# Fixture.create(id: 291, name: '', week_id: 30)
# Fixture.create(id: 292, name: '', week_id: 30)
# Fixture.create(id: 293, name: '', week_id: 30)
# Fixture.create(id: 294, name: '', week_id: 30)
# Fixture.create(id: 295, name: '', week_id: 30)
# Fixture.create(id: 296, name: '', week_id: 30)
# Fixture.create(id: 297, name: '', week_id: 30)
# Fixture.create(id: 298, name: '', week_id: 30)
# Fixture.create(id: 299, name: '', week_id: 30)
# Fixture.create(id: 300, name: '', week_id: 30)
#
# Fixture.create(id: 301, name: '', week_id: 31)
# Fixture.create(id: 302, name: '', week_id: 31)
# Fixture.create(id: 303, name: '', week_id: 31)
# Fixture.create(id: 304, name: '', week_id: 31)
# Fixture.create(id: 305, name: '', week_id: 31)
# Fixture.create(id: 306, name: '', week_id: 31)
# Fixture.create(id: 307, name: '', week_id: 31)
# Fixture.create(id: 308, name: '', week_id: 31)
# Fixture.create(id: 309, name: '', week_id: 31)
# Fixture.create(id: 310, name: '', week_id: 31)
#
# Fixture.create(id: 311, name: '', week_id: 32)
# Fixture.create(id: 312, name: '', week_id: 32)
# Fixture.create(id: 313, name: '', week_id: 32)
# Fixture.create(id: 314, name: '', week_id: 32)
# Fixture.create(id: 315, name: '', week_id: 32)
# Fixture.create(id: 316, name: '', week_id: 32)
# Fixture.create(id: 317, name: '', week_id: 32)
# Fixture.create(id: 318, name: '', week_id: 32)
# Fixture.create(id: 319, name: '', week_id: 32)
# Fixture.create(id: 320, name: '', week_id: 32)
#
# Fixture.create(id: 321, name: '', week_id: 33)
# Fixture.create(id: 322, name: '', week_id: 33)
# Fixture.create(id: 323, name: '', week_id: 33)
# Fixture.create(id: 324, name: '', week_id: 33)
# Fixture.create(id: 325, name: '', week_id: 33)
# Fixture.create(id: 326, name: '', week_id: 33)
# Fixture.create(id: 327, name: '', week_id: 33)
# Fixture.create(id: 328, name: '', week_id: 33)
# Fixture.create(id: 329, name: '', week_id: 33)
# Fixture.create(id: 330, name: '', week_id: 33)
#
# Fixture.create(id: 331, name: '', week_id: 34)
# Fixture.create(id: 332, name: '', week_id: 34)
# Fixture.create(id: 333, name: '', week_id: 34)
# Fixture.create(id: 334, name: '', week_id: 34)
# Fixture.create(id: 335, name: '', week_id: 34)
# Fixture.create(id: 336, name: '', week_id: 34)
# Fixture.create(id: 337, name: '', week_id: 34)
# Fixture.create(id: 338, name: '', week_id: 34)
# Fixture.create(id: 339, name: '', week_id: 34)
# Fixture.create(id: 340, name: '', week_id: 34)
#
# Fixture.create(id: 341, name: '', week_id: 35)
# Fixture.create(id: 342, name: '', week_id: 35)
# Fixture.create(id: 343, name: '', week_id: 35)
# Fixture.create(id: 344, name: '', week_id: 35)
# Fixture.create(id: 345, name: '', week_id: 35)
# Fixture.create(id: 346, name: '', week_id: 35)
# Fixture.create(id: 347, name: '', week_id: 35)
# Fixture.create(id: 348, name: '', week_id: 35)
# Fixture.create(id: 349, name: '', week_id: 35)
# Fixture.create(id: 350, name: '', week_id: 35)
#
# Fixture.create(id: 351, name: '', week_id: 36)
# Fixture.create(id: 352, name: '', week_id: 36)
# Fixture.create(id: 353, name: '', week_id: 36)
# Fixture.create(id: 354, name: '', week_id: 36)
# Fixture.create(id: 355, name: '', week_id: 36)
# Fixture.create(id: 356, name: '', week_id: 36)
# Fixture.create(id: 357, name: '', week_id: 36)
# Fixture.create(id: 358, name: '', week_id: 36)
# Fixture.create(id: 359, name: '', week_id: 36)
# Fixture.create(id: 360, name: '', week_id: 36)
#
# Fixture.create(id: 361, name: '', week_id: 37)
# Fixture.create(id: 362, name: '', week_id: 37)
# Fixture.create(id: 363, name: '', week_id: 37)
# Fixture.create(id: 364, name: '', week_id: 37)
# Fixture.create(id: 365, name: '', week_id: 37)
# Fixture.create(id: 366, name: '', week_id: 37)
# Fixture.create(id: 367, name: '', week_id: 37)
# Fixture.create(id: 368, name: '', week_id: 37)
# Fixture.create(id: 369, name: '', week_id: 37)
# Fixture.create(id: 370, name: '', week_id: 37)
#
# Fixture.create(id: 371, name: '', week_id: 38)
# Fixture.create(id: 372, name: '', week_id: 38)
# Fixture.create(id: 373, name: '', week_id: 38)
# Fixture.create(id: 374, name: '', week_id: 38)
# Fixture.create(id: 375, name: '', week_id: 38)
# Fixture.create(id: 376, name: '', week_id: 38)
# Fixture.create(id: 377, name: '', week_id: 38)
# Fixture.create(id: 378, name: '', week_id: 38)
# Fixture.create(id: 379, name: '', week_id: 38)
# Fixture.create(id: 380, name: '', week_id: 38)
