Fixture.delete_all

Fixture.create(id: 1,   name: 'BOU-SHU', week_id: 1)
Fixture.create(id: 2,   name: 'BUR-SOU', week_id: 1)
Fixture.create(id: 3,   name: 'CRY-EVE', week_id: 1)
Fixture.create(id: 4,   name: 'LEI-WOL', week_id: 1)
Fixture.create(id: 5,   name: 'LIV-NOR', week_id: 1)
Fixture.create(id: 6,   name: 'MUN-CHE', week_id: 1)
Fixture.create(id: 7,   name: 'NEW-ARS', week_id: 1)
Fixture.create(id: 8,   name: 'TOT-AST', week_id: 1)
Fixture.create(id: 9,   name: 'WAT-BRI', week_id: 1)
Fixture.create(id: 10,  name: 'WHA-MCI', week_id: 1)

Fixture.create(id: 11,  name: 'ARS-BUR', week_id: 2)
Fixture.create(id: 12,  name: 'AST-BOU', week_id: 2)
Fixture.create(id: 13,  name: 'BRI-WHA', week_id: 2)
Fixture.create(id: 14,  name: 'CHE-LEI', week_id: 2)
Fixture.create(id: 15,  name: 'EVE-WAT', week_id: 2)
Fixture.create(id: 16,  name: 'MCI-TOT', week_id: 2)
Fixture.create(id: 17,  name: 'NOR-NEW', week_id: 2)
Fixture.create(id: 18,  name: 'SHU-CRY', week_id: 2)
Fixture.create(id: 19,  name: 'SOU-LIV', week_id: 2)
Fixture.create(id: 20,  name: 'WOL-MUN', week_id: 2)

Fixture.create(id: 21,  name: 'AST-EVE', week_id: 3)
Fixture.create(id: 22,  name: 'BOU-MCI', week_id: 3)
Fixture.create(id: 23,  name: 'BRI-SOU', week_id: 3)
Fixture.create(id: 24,  name: 'LIV-ARS', week_id: 3)
Fixture.create(id: 25,  name: 'MUN-CRY', week_id: 3)
Fixture.create(id: 26,  name: 'NOR-CHE', week_id: 3)
Fixture.create(id: 27,  name: 'SHU-LEI', week_id: 3)
Fixture.create(id: 28,  name: 'TOT-NEW', week_id: 3)
Fixture.create(id: 29,  name: 'WAT-WHA', week_id: 3)
Fixture.create(id: 30,  name: 'WOL-BUR', week_id: 3)

Fixture.create(id: 31,  name: 'ARS-TOT', week_id: 4)
Fixture.create(id: 32,  name: 'BUR-LIV', week_id: 4)
Fixture.create(id: 33,  name: 'CHE-SHU', week_id: 4)
Fixture.create(id: 34,  name: 'CRY-AST', week_id: 4)
Fixture.create(id: 35,  name: 'EVE-WOL', week_id: 4)
Fixture.create(id: 36,  name: 'LEI-BOU', week_id: 4)
Fixture.create(id: 37,  name: 'MCI-BRI', week_id: 4)
Fixture.create(id: 38,  name: 'NEW-WAT', week_id: 4)
Fixture.create(id: 39,  name: 'SOU-MUN', week_id: 4)
Fixture.create(id: 40,  name: 'WHA-NOR', week_id: 4)

Fixture.create(id: 41,  name: 'AST-WHA', week_id: 5)
Fixture.create(id: 42,  name: 'BOU-EVE', week_id: 5)
Fixture.create(id: 43,  name: 'BRI-BUR', week_id: 5)
Fixture.create(id: 44,  name: 'LIV-NEW', week_id: 5)
Fixture.create(id: 45,  name: 'MUN-LEI', week_id: 5)
Fixture.create(id: 46,  name: 'NOR-MCI', week_id: 5)
Fixture.create(id: 47,  name: 'SHU-SOU', week_id: 5)
Fixture.create(id: 48,  name: 'TOT-CRY', week_id: 5)
Fixture.create(id: 49,  name: 'WAT-ARS', week_id: 5)
Fixture.create(id: 50,  name: 'WOL-CHE', week_id: 5)

Fixture.create(id: 51,  name: 'ARS-AST', week_id: 6)
Fixture.create(id: 52,  name: 'BUR-NOR', week_id: 6)
Fixture.create(id: 53,  name: 'CHE-LIV', week_id: 6)
Fixture.create(id: 54,  name: 'CRY-WOL', week_id: 6)
Fixture.create(id: 55,  name: 'EVE-SHU', week_id: 6)
Fixture.create(id: 56,  name: 'LEI-TOT', week_id: 6)
Fixture.create(id: 57,  name: 'MCI-WAT', week_id: 6)
Fixture.create(id: 58,  name: 'NEW-BRI', week_id: 6)
Fixture.create(id: 59,  name: 'SOU-BOU', week_id: 6)
Fixture.create(id: 60,  name: 'WHA-MUN', week_id: 6)

Fixture.create(id: 61,  name: 'AST-BUR', week_id: 7)
Fixture.create(id: 62,  name: 'BOU-WHA', week_id: 7)
Fixture.create(id: 63,  name: 'CHE-BRI', week_id: 7)
Fixture.create(id: 64,  name: 'CRY-NOR', week_id: 7)
Fixture.create(id: 65,  name: 'EVE-MCI', week_id: 7)
Fixture.create(id: 66,  name: 'LEI-NEW', week_id: 7)
Fixture.create(id: 67,  name: 'MUN-ARS', week_id: 7)
Fixture.create(id: 68,  name: 'SHU-LIV', week_id: 7)
Fixture.create(id: 69,  name: 'TOT-SOU', week_id: 7)
Fixture.create(id: 70,  name: 'WOL-WAT', week_id: 7)

Fixture.create(id: 71,  name: 'ARS-BOU', week_id: 8)
Fixture.create(id: 72,  name: 'BRI-TOT', week_id: 8)
Fixture.create(id: 73,  name: 'BUR-EVE', week_id: 8)
Fixture.create(id: 74,  name: 'LIV-LEI', week_id: 8)
Fixture.create(id: 75,  name: 'MCI-WOL', week_id: 8)
Fixture.create(id: 76,  name: 'NEW-MUN', week_id: 8)
Fixture.create(id: 77,  name: 'NOR-AST', week_id: 8)
Fixture.create(id: 78,  name: 'SOU-CHE', week_id: 8)
Fixture.create(id: 79,  name: 'WAT-SHU', week_id: 8)
Fixture.create(id: 80,  name: 'WHA-CRY', week_id: 8)

Fixture.create(id: 81,  name: 'AST-BRI', week_id: 9)
Fixture.create(id: 82,  name: 'BOU-NOR', week_id: 9)
Fixture.create(id: 83,  name: 'CHE-NEW', week_id: 9)
Fixture.create(id: 84,  name: 'CRY-MCI', week_id: 9)
Fixture.create(id: 85,  name: 'EVE-WHA', week_id: 9)
Fixture.create(id: 86,  name: 'LEI-BUR', week_id: 9)
Fixture.create(id: 87,  name: 'MUN-LIV', week_id: 9)
Fixture.create(id: 88,  name: 'SHU-ARS', week_id: 9)
Fixture.create(id: 89,  name: 'TOT-WAT', week_id: 9)
Fixture.create(id: 90,  name: 'WOL-SOU', week_id: 9)

Fixture.create(id: 91,  name: 'ARS-CRY', week_id: 10)
Fixture.create(id: 92,  name: 'BRI-EVE', week_id: 10)
Fixture.create(id: 93,  name: 'BUR-CHE', week_id: 10)
Fixture.create(id: 94,  name: 'LIV-TOT', week_id: 10)
Fixture.create(id: 95,  name: 'MCI-AST', week_id: 10)
Fixture.create(id: 96,  name: 'NEW-WOL', week_id: 10)
Fixture.create(id: 97,  name: 'NOR-MUN', week_id: 10)
Fixture.create(id: 98,  name: 'SOU-LEI', week_id: 10)
Fixture.create(id: 99,  name: 'WAT-BOU', week_id: 10)
Fixture.create(id: 100, name: 'WHA-SHU', week_id: 10)

# Fixture.create(id: 101, name: '', week_id: 11)
# Fixture.create(id: 102, name: '', week_id: 11)
# Fixture.create(id: 103, name: '', week_id: 11)
# Fixture.create(id: 104, name: '', week_id: 11)
# Fixture.create(id: 105, name: '', week_id: 11)
# Fixture.create(id: 106, name: '', week_id: 11)
# Fixture.create(id: 107, name: '', week_id: 11)
# Fixture.create(id: 108, name: '', week_id: 11)
# Fixture.create(id: 109, name: '', week_id: 11)
# Fixture.create(id: 110, name: '', week_id: 11)
#
# Fixture.create(id: 111, name: '', week_id: 12)
# Fixture.create(id: 112, name: '', week_id: 12)
# Fixture.create(id: 113, name: '', week_id: 12)
# Fixture.create(id: 114, name: '', week_id: 12)
# Fixture.create(id: 115, name: '', week_id: 12)
# Fixture.create(id: 116, name: '', week_id: 12)
# Fixture.create(id: 117, name: '', week_id: 12)
# Fixture.create(id: 118, name: '', week_id: 12)
# Fixture.create(id: 119, name: '', week_id: 12)
# Fixture.create(id: 120, name: '', week_id: 12)
#
# Fixture.create(id: 121, name: '', week_id: 13)
# Fixture.create(id: 122, name: '', week_id: 13)
# Fixture.create(id: 123, name: '', week_id: 13)
# Fixture.create(id: 124, name: '', week_id: 13)
# Fixture.create(id: 125, name: '', week_id: 13)
# Fixture.create(id: 126, name: '', week_id: 13)
# Fixture.create(id: 127, name: '', week_id: 13)
# Fixture.create(id: 128, name: '', week_id: 13)
# Fixture.create(id: 129, name: '', week_id: 13)
# Fixture.create(id: 130, name: '', week_id: 13)
#
# Fixture.create(id: 131, name: '', week_id: 14)
# Fixture.create(id: 132, name: '', week_id: 14)
# Fixture.create(id: 133, name: '', week_id: 14)
# Fixture.create(id: 134, name: '', week_id: 14)
# Fixture.create(id: 135, name: '', week_id: 14)
# Fixture.create(id: 136, name: '', week_id: 14)
# Fixture.create(id: 137, name: '', week_id: 14)
# Fixture.create(id: 138, name: '', week_id: 14)
# Fixture.create(id: 139, name: '', week_id: 14)
# Fixture.create(id: 140, name: '', week_id: 14)
#
# Fixture.create(id: 141, name: '', week_id: 15)
# Fixture.create(id: 142, name: '', week_id: 15)
# Fixture.create(id: 143, name: '', week_id: 15)
# Fixture.create(id: 144, name: '', week_id: 15)
# Fixture.create(id: 145, name: '', week_id: 15)
# Fixture.create(id: 146, name: '', week_id: 15)
# Fixture.create(id: 147, name: '', week_id: 15)
# Fixture.create(id: 148, name: '', week_id: 15)
# Fixture.create(id: 149, name: '', week_id: 15)
# Fixture.create(id: 150, name: '', week_id: 15)
#
# Fixture.create(id: 151, name: '', week_id: 16)
# Fixture.create(id: 152, name: '', week_id: 16)
# Fixture.create(id: 153, name: '', week_id: 16)
# Fixture.create(id: 154, name: '', week_id: 16)
# Fixture.create(id: 160, name: '', week_id: 16)
# Fixture.create(id: 155, name: '', week_id: 16)
# Fixture.create(id: 156, name: '', week_id: 16)
# Fixture.create(id: 157, name: '', week_id: 16)
# Fixture.create(id: 158, name: '', week_id: 16)
# Fixture.create(id: 159, name: '', week_id: 16)
#
# Fixture.create(id: 161, name: '', week_id: 17)
# Fixture.create(id: 162, name: '', week_id: 17)
# Fixture.create(id: 163, name: '', week_id: 17)
# Fixture.create(id: 164, name: '', week_id: 17)
# Fixture.create(id: 165, name: '', week_id: 17)
# Fixture.create(id: 166, name: '', week_id: 17)
# Fixture.create(id: 167, name: '', week_id: 17)
# Fixture.create(id: 168, name: '', week_id: 17)
# Fixture.create(id: 169, name: '', week_id: 17)
# Fixture.create(id: 170, name: '', week_id: 17)
#
# Fixture.create(id: 171, name: '', week_id: 18)
# Fixture.create(id: 172, name: '', week_id: 18)
# Fixture.create(id: 173, name: '', week_id: 18)
# Fixture.create(id: 174, name: '', week_id: 18)
# Fixture.create(id: 175, name: '', week_id: 18)
# Fixture.create(id: 176, name: '', week_id: 18)
# Fixture.create(id: 177, name: '', week_id: 18)
# Fixture.create(id: 178, name: '', week_id: 18)
# Fixture.create(id: 179, name: '', week_id: 18)
# Fixture.create(id: 180, name: '', week_id: 18)
#
# Fixture.create(id: 181, name: '', week_id: 19)
# Fixture.create(id: 182, name: '', week_id: 19)
# Fixture.create(id: 183, name: '', week_id: 19)
# Fixture.create(id: 184, name: '', week_id: 19)
# Fixture.create(id: 185, name: '', week_id: 19)
# Fixture.create(id: 186, name: '', week_id: 19)
# Fixture.create(id: 187, name: '', week_id: 19)
# Fixture.create(id: 188, name: '', week_id: 19)
# Fixture.create(id: 189, name: '', week_id: 19)
# Fixture.create(id: 190, name: '', week_id: 19)
#
# Fixture.create(id: 191, name: 'BRI-EVE', week_id: 20)
# Fixture.create(id: 192, name: 'BUR-WHA', week_id: 20)
# Fixture.create(id: 193, name: 'CRY-CHE', week_id: 20)
# Fixture.create(id: 194, name: 'FUL-HUD', week_id: 20)
# Fixture.create(id: 195, name: 'LEI-CAR', week_id: 20)
# Fixture.create(id: 196, name: 'LIV-ARS', week_id: 20)
# Fixture.create(id: 197, name: 'MUN-BOU', week_id: 20)
# Fixture.create(id: 198, name: 'SOU-MCI', week_id: 20)
# Fixture.create(id: 199, name: 'TOT-WOL', week_id: 20)
# Fixture.create(id: 200, name: 'WAT-NEW', week_id: 20)
#
# Fixture.create(id: 201, name: 'ARS-FUL', week_id: 21)
# Fixture.create(id: 202, name: 'BOU-WAT', week_id: 21)
# Fixture.create(id: 203, name: 'CAR-TOT', week_id: 21)
# Fixture.create(id: 204, name: 'CHE-SOU', week_id: 21)
# Fixture.create(id: 205, name: 'EVE-LEI', week_id: 21)
# Fixture.create(id: 206, name: 'HUD-BUR', week_id: 21)
# Fixture.create(id: 207, name: 'MCI-LIV', week_id: 21)
# Fixture.create(id: 208, name: 'NEW-MUN', week_id: 21)
# Fixture.create(id: 209, name: 'WHA-BRI', week_id: 21)
# Fixture.create(id: 210, name: 'WOL-CRY', week_id: 21)
#
# Fixture.create(id: 211, name: 'BRI-LIV', week_id: 22)
# Fixture.create(id: 212, name: 'BUR-FUL', week_id: 22)
# Fixture.create(id: 213, name: 'CAR-HUD', week_id: 22)
# Fixture.create(id: 214, name: 'CHE-NEW', week_id: 22)
# Fixture.create(id: 215, name: 'CRY-WAT', week_id: 22)
# Fixture.create(id: 216, name: 'EVE-BOU', week_id: 22)
# Fixture.create(id: 217, name: 'LEI-SOU', week_id: 22)
# Fixture.create(id: 218, name: 'MCI-WOL', week_id: 22)
# Fixture.create(id: 219, name: 'TOT-MUN', week_id: 22)
# Fixture.create(id: 220, name: 'WHA-ARS', week_id: 22)
#
# Fixture.create(id: 221, name: 'ARS-CHE', week_id: 23)
# Fixture.create(id: 222, name: 'BOU-WHA', week_id: 23)
# Fixture.create(id: 223, name: 'FUL-TOT', week_id: 23)
# Fixture.create(id: 224, name: 'HUD-MCI', week_id: 23)
# Fixture.create(id: 225, name: 'LIV-CRY', week_id: 23)
# Fixture.create(id: 226, name: 'MUN-BRI', week_id: 23)
# Fixture.create(id: 227, name: 'NEW-CAR', week_id: 23)
# Fixture.create(id: 228, name: 'SOU-EVE', week_id: 23)
# Fixture.create(id: 229, name: 'WAT-BUR', week_id: 23)
# Fixture.create(id: 230, name: 'WOL-LEI', week_id: 23)
#
# Fixture.create(id: 231, name: 'ARS-CAR', week_id: 24)
# Fixture.create(id: 232, name: 'BOU-CHE', week_id: 24)
# Fixture.create(id: 233, name: 'FUL-BRI', week_id: 24)
# Fixture.create(id: 234, name: 'HUD-EVE', week_id: 24)
# Fixture.create(id: 235, name: 'LIV-LEI', week_id: 24)
# Fixture.create(id: 236, name: 'MUN-BUR', week_id: 24)
# Fixture.create(id: 237, name: 'NEW-MCI', week_id: 24)
# Fixture.create(id: 238, name: 'SOU-CRY', week_id: 24)
# Fixture.create(id: 239, name: 'TOT-WAT', week_id: 24)
# Fixture.create(id: 240, name: 'WOL-WHA', week_id: 24)
#
# Fixture.create(id: 241, name: 'BRI-WAT', week_id: 25)
# Fixture.create(id: 242, name: 'BUR-SOU', week_id: 25)
# Fixture.create(id: 243, name: 'CAR-BOU', week_id: 25)
# Fixture.create(id: 244, name: 'CHE-HUD', week_id: 25)
# Fixture.create(id: 245, name: 'CRY-FUL', week_id: 25)
# Fixture.create(id: 246, name: 'EVE-WOL', week_id: 25)
# Fixture.create(id: 247, name: 'LEI-MUN', week_id: 25)
# Fixture.create(id: 248, name: 'MCI-ARS', week_id: 25)
# Fixture.create(id: 249, name: 'TOT-NEW', week_id: 25)
# Fixture.create(id: 250, name: 'WHA-LIV', week_id: 25)
#
# Fixture.create(id: 251, name: 'BRI-BUR', week_id: 26)
# Fixture.create(id: 252, name: 'CRY-WHA', week_id: 26)
# Fixture.create(id: 253, name: 'FUL-MUN', week_id: 26)
# Fixture.create(id: 254, name: 'HUD-ARS', week_id: 26)
# Fixture.create(id: 255, name: 'LIV-BOU', week_id: 26)
# Fixture.create(id: 256, name: 'MCI-CHE', week_id: 26)
# Fixture.create(id: 257, name: 'SOU-CAR', week_id: 26)
# Fixture.create(id: 258, name: 'TOT-LEI', week_id: 26)
# Fixture.create(id: 259, name: 'WAT-EVE', week_id: 26)
# Fixture.create(id: 260, name: 'WOL-NEW', week_id: 26)
#
# Fixture.create(id: 261, name: 'ARS-SOU', week_id: 27)
# Fixture.create(id: 262, name: 'BOU-WOL', week_id: 27)
# Fixture.create(id: 263, name: 'BUR-TOT', week_id: 27)
# Fixture.create(id: 264, name: 'CAR-WAT', week_id: 27)
# Fixture.create(id: 265, name: 'CHE-BRI', week_id: 27)
# Fixture.create(id: 266, name: 'EVE-MCI', week_id: 27)
# Fixture.create(id: 267, name: 'LEI-CRY', week_id: 27)
# Fixture.create(id: 268, name: 'MUN-LIV', week_id: 27)
# Fixture.create(id: 269, name: 'NEW-HUD', week_id: 27)
# Fixture.create(id: 270, name: 'WHA-FUL', week_id: 27)
#
# Fixture.create(id: 271, name: 'ARS-BOU', week_id: 28)
# Fixture.create(id: 272, name: 'CAR-EVE', week_id: 28)
# Fixture.create(id: 273, name: 'CHE-TOT', week_id: 28)
# Fixture.create(id: 274, name: 'CRY-MUN', week_id: 28)
# Fixture.create(id: 275, name: 'HUD-WOL', week_id: 28)
# Fixture.create(id: 276, name: 'LEI-BRI', week_id: 28)
# Fixture.create(id: 277, name: 'LIV-WAT', week_id: 28)
# Fixture.create(id: 278, name: 'MCI-WHA', week_id: 28)
# Fixture.create(id: 279, name: 'NEW-BUR', week_id: 28)
# Fixture.create(id: 280, name: 'SOU-FUL', week_id: 28)
#
# Fixture.create(id: 281, name: 'BOU-MCI', week_id: 29)
# Fixture.create(id: 282, name: 'BRI-HUD', week_id: 29)
# Fixture.create(id: 283, name: 'BUR-CRY', week_id: 29)
# Fixture.create(id: 284, name: 'EVE-LIV', week_id: 29)
# Fixture.create(id: 285, name: 'FUL-CHE', week_id: 29)
# Fixture.create(id: 286, name: 'MUN-SOU', week_id: 29)
# Fixture.create(id: 287, name: 'TOT-ARS', week_id: 29)
# Fixture.create(id: 288, name: 'WAT-LEI', week_id: 29)
# Fixture.create(id: 289, name: 'WHA-NEW', week_id: 29)
# Fixture.create(id: 290, name: 'WOL-CAR', week_id: 29)
#
# Fixture.create(id: 291, name: 'ARS-MUN', week_id: 30)
# Fixture.create(id: 292, name: 'CAR-WHA', week_id: 30)
# Fixture.create(id: 293, name: 'CHE-WOL', week_id: 30)
# Fixture.create(id: 294, name: 'CRY-BRI', week_id: 30)
# Fixture.create(id: 295, name: 'HUD-BOU', week_id: 30)
# Fixture.create(id: 296, name: 'LEI-FUL', week_id: 30)
# Fixture.create(id: 297, name: 'LIV-BUR', week_id: 30)
# Fixture.create(id: 298, name: 'MCI-WAT', week_id: 30)
# Fixture.create(id: 299, name: 'NEW-EVE', week_id: 30)
# Fixture.create(id: 300, name: 'SOU-TOT', week_id: 30)
#
# Fixture.create(id: 301, name: 'BOU-NEW', week_id: 31)
# Fixture.create(id: 302, name: 'BRI-CAR', week_id: 31)
# Fixture.create(id: 303, name: 'BUR-LEI', week_id: 31)
# Fixture.create(id: 304, name: 'EVE-CHE', week_id: 31)
# Fixture.create(id: 305, name: 'FUL-LIV', week_id: 31)
# Fixture.create(id: 306, name: 'MUN-MCI', week_id: 31)
# Fixture.create(id: 307, name: 'TOT-CRY', week_id: 31)
# Fixture.create(id: 308, name: 'WAT-SOU', week_id: 31)
# Fixture.create(id: 309, name: 'WHA-HUD', week_id: 31)
# Fixture.create(id: 310, name: 'WOL-ARS', week_id: 31)
#
# Fixture.create(id: 311, name: 'ARS-NEW', week_id: 32)
# Fixture.create(id: 312, name: 'BRI-SOU', week_id: 32)
# Fixture.create(id: 313, name: 'BUR-WOL', week_id: 32)
# Fixture.create(id: 314, name: 'CAR-CHE', week_id: 32)
# Fixture.create(id: 315, name: 'CRY-HUD', week_id: 32)
# Fixture.create(id: 316, name: 'FUL-MCI', week_id: 32)
# Fixture.create(id: 317, name: 'LEI-BOU', week_id: 32)
# Fixture.create(id: 318, name: 'LIV-TOT', week_id: 32)
# Fixture.create(id: 319, name: 'MUN-WAT', week_id: 32)
# Fixture.create(id: 320, name: 'WHA-EVE', week_id: 32)
#
# Fixture.create(id: 321, name: 'BOU-BUR', week_id: 33)
# Fixture.create(id: 322, name: 'CHE-WHA', week_id: 33)
# Fixture.create(id: 323, name: 'EVE-ARS', week_id: 33)
# Fixture.create(id: 324, name: 'HUD-LEI', week_id: 33)
# Fixture.create(id: 325, name: 'MCI-CAR', week_id: 33)
# Fixture.create(id: 326, name: 'NEW-CRY', week_id: 33)
# Fixture.create(id: 327, name: 'SOU-LIV', week_id: 33)
# Fixture.create(id: 328, name: 'TOT-BRI', week_id: 33)
# Fixture.create(id: 329, name: 'WAT-FUL', week_id: 33)
# Fixture.create(id: 330, name: 'WOL-MUN', week_id: 33)
#
# Fixture.create(id: 331, name: 'BRI-BOU', week_id: 34)
# Fixture.create(id: 332, name: 'BUR-CAR', week_id: 34)
# Fixture.create(id: 333, name: 'CRY-MCI', week_id: 34)
# Fixture.create(id: 334, name: 'FUL-EVE', week_id: 34)
# Fixture.create(id: 335, name: 'LEI-NEW', week_id: 34)
# Fixture.create(id: 336, name: 'LIV-CHE', week_id: 34)
# Fixture.create(id: 337, name: 'MUN-WHA', week_id: 34)
# Fixture.create(id: 338, name: 'SOU-WOL', week_id: 34)
# Fixture.create(id: 339, name: 'TOT-HUD', week_id: 34)
# Fixture.create(id: 340, name: 'WAT-ARS', week_id: 34)
#
# Fixture.create(id: 341, name: 'ARS-CRY', week_id: 35)
# Fixture.create(id: 342, name: 'BOU-FUL', week_id: 35)
# Fixture.create(id: 343, name: 'CAR-LIV', week_id: 35)
# Fixture.create(id: 344, name: 'CHE-BUR', week_id: 35)
# Fixture.create(id: 345, name: 'EVE-MUN', week_id: 35)
# Fixture.create(id: 346, name: 'HUD-WAT', week_id: 35)
# Fixture.create(id: 347, name: 'MCI-TOT', week_id: 35)
# Fixture.create(id: 348, name: 'NEW-SOU', week_id: 35)
# Fixture.create(id: 349, name: 'WHA-LEI', week_id: 35)
# Fixture.create(id: 350, name: 'WOL-BRI', week_id: 35)
#
# Fixture.create(id: 351, name: 'BRI-NEW', week_id: 36)
# Fixture.create(id: 352, name: 'BUR-MCI', week_id: 36)
# Fixture.create(id: 353, name: 'CRY-EVE', week_id: 36)
# Fixture.create(id: 354, name: 'FUL-CAR', week_id: 36)
# Fixture.create(id: 355, name: 'LEI-ARS', week_id: 36)
# Fixture.create(id: 356, name: 'LIV-HUD', week_id: 36)
# Fixture.create(id: 357, name: 'MUN-CHE', week_id: 36)
# Fixture.create(id: 358, name: 'SOU-BOU', week_id: 36)
# Fixture.create(id: 359, name: 'TOT-WHA', week_id: 36)
# Fixture.create(id: 360, name: 'WAT-WOL', week_id: 36)
#
# Fixture.create(id: 361, name: 'ARS-BRI', week_id: 37)
# Fixture.create(id: 362, name: 'BOU-TOT', week_id: 37)
# Fixture.create(id: 363, name: 'CAR-CRY', week_id: 37)
# Fixture.create(id: 364, name: 'CHE-WAT', week_id: 37)
# Fixture.create(id: 365, name: 'EVE-BUR', week_id: 37)
# Fixture.create(id: 366, name: 'HUD-MUN', week_id: 37)
# Fixture.create(id: 367, name: 'MCI-LEI', week_id: 37)
# Fixture.create(id: 368, name: 'NEW-LIV', week_id: 37)
# Fixture.create(id: 369, name: 'WHA-SOU', week_id: 37)
# Fixture.create(id: 370, name: 'WOL-FUL', week_id: 37)
#
# Fixture.create(id: 371, name: 'BRI-MCI', week_id: 38)
# Fixture.create(id: 372, name: 'BUR-ARS', week_id: 38)
# Fixture.create(id: 373, name: 'CRY-BOU', week_id: 38)
# Fixture.create(id: 374, name: 'FUL-NEW', week_id: 38)
# Fixture.create(id: 375, name: 'LEI-CHE', week_id: 38)
# Fixture.create(id: 376, name: 'LIV-WOL', week_id: 38)
# Fixture.create(id: 377, name: 'MUN-CAR', week_id: 38)
# Fixture.create(id: 378, name: 'SOU-HUD', week_id: 38)
# Fixture.create(id: 379, name: 'TOT-EVE', week_id: 38)
# Fixture.create(id: 380, name: 'WAT-WHA', week_id: 38)
#