Team.delete_all

Team.find_or_create_by_id(id: 1,  feed_id: 9002, abbreviation: 'ars', name: 'Arsenal')
Team.find_or_create_by_id(id: 2,  feed_id: 9008, abbreviation: 'ast', name: 'Aston Villa')
Team.find_or_create_by_id(id: 3,  feed_id: 9072, abbreviation: 'bur', name: 'Burnley')
Team.find_or_create_by_id(id: 4,  feed_id: 9092, abbreviation: 'che', name: 'Chelsea')
Team.find_or_create_by_id(id: 5,  feed_id: 9127, abbreviation: 'cry', name: 'Crystal Palace')
Team.find_or_create_by_id(id: 6,  feed_id: 9158, abbreviation: 'eve', name: 'Everton')
Team.find_or_create_by_id(id: 7,  feed_id: 9221, abbreviation: 'hul', name: 'Hull')
Team.find_or_create_by_id(id: 8,  feed_id: 9240, abbreviation: 'lei', name: 'Leicester')
Team.find_or_create_by_id(id: 9,  feed_id: 9249, abbreviation: 'liv', name: 'Liverpool')
Team.find_or_create_by_id(id: 10, feed_id: 9259, abbreviation: 'mci', name: 'Man City')
Team.find_or_create_by_id(id: 11, feed_id: 9260, abbreviation: 'mun', name: 'Man Utd')
Team.find_or_create_by_id(id: 12, feed_id: 9287, abbreviation: 'new', name: 'Newcastle')
Team.find_or_create_by_id(id: 13, feed_id: 9318, abbreviation: 'qpr', name: 'QPR')
Team.find_or_create_by_id(id: 14, feed_id: 9363, abbreviation: 'sou', name: 'Southampton')
Team.find_or_create_by_id(id: 15, feed_id: 9378, abbreviation: 'sto', name: 'Stoke')
Team.find_or_create_by_id(id: 16, feed_id: 9384, abbreviation: 'sun', name: 'Sunderland')
Team.find_or_create_by_id(id: 17, feed_id: 9387, abbreviation: 'swa', name: 'Swansea')
Team.find_or_create_by_id(id: 18, feed_id: 9406, abbreviation: 'tot', name: 'Tottenham')
Team.find_or_create_by_id(id: 19, feed_id: 9426, abbreviation: 'wbr', name: 'West Brom')
Team.find_or_create_by_id(id: 20, feed_id: 9427, abbreviation: 'wha', name: 'West Ham')
