Team.delete_all

Team.find_or_create_by_id(id: 1,  external_id: 9002, abbreviation: 'ars', name: 'Arsenal')
Team.find_or_create_by_id(id: 2,  external_id: 9008, abbreviation: 'ast', name: 'Aston Villa')
Team.find_or_create_by_id(id: 3,  external_id: nil,  abbreviation: 'bou', name: 'Bournemouth')
Team.find_or_create_by_id(id: 4,  external_id: 9092, abbreviation: 'che', name: 'Chelsea')
Team.find_or_create_by_id(id: 5,  external_id: 9127, abbreviation: 'cry', name: 'Crystal Palace')
Team.find_or_create_by_id(id: 6,  external_id: 9158, abbreviation: 'eve', name: 'Everton')
Team.find_or_create_by_id(id: 7,  external_id: 9240, abbreviation: 'lei', name: 'Leicester')
Team.find_or_create_by_id(id: 8,  external_id: 9249, abbreviation: 'liv', name: 'Liverpool')
Team.find_or_create_by_id(id: 9,  external_id: 9259, abbreviation: 'mci', name: 'Man City')
Team.find_or_create_by_id(id: 10, external_id: 9260, abbreviation: 'mun', name: 'Man Utd')
Team.find_or_create_by_id(id: 11, external_id: 9287, abbreviation: 'new', name: 'Newcastle')
Team.find_or_create_by_id(id: 12, external_id: nil,  abbreviation: 'nor', name: 'Norwich')
Team.find_or_create_by_id(id: 13, external_id: 9363, abbreviation: 'sou', name: 'Southampton')
Team.find_or_create_by_id(id: 14, external_id: 9378, abbreviation: 'sto', name: 'Stoke')
Team.find_or_create_by_id(id: 15, external_id: 9384, abbreviation: 'sun', name: 'Sunderland')
Team.find_or_create_by_id(id: 16, external_id: 9387, abbreviation: 'swa', name: 'Swansea')
Team.find_or_create_by_id(id: 17, external_id: 9406, abbreviation: 'tot', name: 'Tottenham')
Team.find_or_create_by_id(id: 18, external_id: nil,  abbreviation: 'wat', name: 'Watford')
Team.find_or_create_by_id(id: 19, external_id: 9426, abbreviation: 'wbr', name: 'West Brom')
Team.find_or_create_by_id(id: 20, external_id: 9427, abbreviation: 'wha', name: 'West Ham')
