Team.delete_all

Team.find_or_create_by_id(:id => 1,  :name => 'Arsenal')
Team.find_or_create_by_id(:id => 2,  :name => 'Aston Villa')
Team.find_or_create_by_id(:id => 3,  :name => 'Cardiff')
Team.find_or_create_by_id(:id => 4,  :name => 'Chelsea')
Team.find_or_create_by_id(:id => 5,  :name => 'Crystal Palace')
Team.find_or_create_by_id(:id => 6,  :name => 'Everton')
Team.find_or_create_by_id(:id => 7,  :name => 'Fulham')
Team.find_or_create_by_id(:id => 8,  :name => 'Hull')
Team.find_or_create_by_id(:id => 9,  :name => 'Liverpool')
Team.find_or_create_by_id(:id => 10, :name => 'Man City')
Team.find_or_create_by_id(:id => 11, :name => 'Man Utd')
Team.find_or_create_by_id(:id => 12, :name => 'Newcastle')
Team.find_or_create_by_id(:id => 13, :name => 'Norwich')
Team.find_or_create_by_id(:id => 14, :name => 'Southampton')
Team.find_or_create_by_id(:id => 15, :name => 'Stoke')
Team.find_or_create_by_id(:id => 16, :name => 'Sunderland')
Team.find_or_create_by_id(:id => 17, :name => 'Swansea')
Team.find_or_create_by_id(:id => 18, :name => 'Tottenham')
Team.find_or_create_by_id(:id => 19, :name => 'West Brom')
Team.find_or_create_by_id(:id => 20, :name => 'West Ham')