Team.delete_all

Team.create(id: 1,  external_id: 9002, abbreviation: 'ars', name: 'Arsenal', short_name: 'Arsenal')
Team.create(id: 2,  external_id: 9053, abbreviation: 'bou', name: 'Bournemouth', short_name: "B'mouth")
Team.create(id: 3,  external_id: 9065, abbreviation: 'bri', name: 'Brighton', short_name: 'Brighton')
Team.create(id: 4,  external_id: 9072, abbreviation: 'bur', name: 'Burnley', short_name: 'Burnley')
Team.create(id: 5,  external_id: 9092, abbreviation: 'che', name: 'Chelsea', short_name: 'Chelsea')
Team.create(id: 6,  external_id: 9127, abbreviation: 'cry', name: 'Crystal Palace', short_name: 'C Palace')
Team.create(id: 7,  external_id: 9158, abbreviation: 'eve', name: 'Everton', short_name: 'Everton')
Team.create(id: 8,  external_id: 9220, abbreviation: 'hud', name: 'Huddersfield', short_name: "Huddsf'ld")
Team.create(id: 9,  external_id: 9240, abbreviation: 'lei', name: 'Leicester', short_name: 'Leicester')
Team.create(id: 10, external_id: 9249, abbreviation: 'liv', name: 'Liverpool', short_name: 'Liverpool')
Team.create(id: 11, external_id: 9259, abbreviation: 'mci', name: 'Man City', short_name: 'Man City')
Team.create(id: 12, external_id: 9260, abbreviation: 'mun', name: 'Man Utd', short_name: 'Man Utd')
Team.create(id: 13, external_id: 9287, abbreviation: 'new', name: 'Newcastle', short_name: 'Newcastle')
Team.create(id: 14, external_id: 9363, abbreviation: 'sou', name: 'Southampton', short_name: "So'ton")
Team.create(id: 15, external_id: 9378, abbreviation: 'sto', name: 'Stoke', short_name: 'Stoke')
Team.create(id: 16, external_id: 9387, abbreviation: 'swa', name: 'Swansea', short_name: 'Swansea')
Team.create(id: 17, external_id: 9406, abbreviation: 'tot', name: 'Tottenham', short_name: 'Tottenham')
Team.create(id: 18, external_id: 9423, abbreviation: 'wat', name: 'Watford', short_name: 'Watford')
Team.create(id: 19, external_id: 9426, abbreviation: 'wbr', name: 'West Brom', short_name: 'West Brom')
Team.create(id: 20, external_id: 9427, abbreviation: 'wha', name: 'West Ham', short_name: 'West Ham')
