Team.delete_all

Team.create(id: 1,  external_id: 9825,  abbreviation: 'ars', name: 'Arsenal',                  short_name: 'Arsenal')
Team.create(id: 2,  external_id: 10252, abbreviation: 'ast', name: 'Aston Villa',              short_name: 'Aston Villa')
Team.create(id: 3,  external_id: 8678,  abbreviation: 'bou', name: 'Bournemouth',              short_name: "B'mouth")
Team.create(id: 4,  external_id: 10204, abbreviation: 'bri', name: 'Brighton and Hove Albion', short_name: 'Brighton')
Team.create(id: 5,  external_id: 8191,  abbreviation: 'bur', name: 'Burnley',                  short_name: 'Burnley')
Team.create(id: 6,  external_id: 8455,  abbreviation: 'che', name: 'Chelsea',                  short_name: 'Chelsea')
Team.create(id: 7,  external_id: 9826,  abbreviation: 'cry', name: 'Crystal Palace',           short_name: 'C Palace')
Team.create(id: 8,  external_id: 8668,  abbreviation: 'eve', name: 'Everton',                  short_name: 'Everton')
Team.create(id: 9,  external_id: 8197,  abbreviation: 'lei', name: 'Leicester City',           short_name: 'Leicester')
Team.create(id: 10, external_id: 8650,  abbreviation: 'liv', name: 'Liverpool',                short_name: 'Liverpool')
Team.create(id: 11, external_id: 8456,  abbreviation: 'mci', name: 'Manchester City',          short_name: 'Man City')
Team.create(id: 12, external_id: 10260, abbreviation: 'mun', name: 'Manchester Utd',           short_name: 'Man Utd')
Team.create(id: 13, external_id: 9850,  abbreviation: 'nor', name: 'Norwich City',             short_name: 'Norwich')
Team.create(id: 14, external_id: 10261, abbreviation: 'new', name: 'Newcastle Utd',            short_name: 'Newcastle')
Team.create(id: 15, external_id: 8657,  abbreviation: 'shu', name: 'Sheffield Utd',            short_name: "Shef Utd")
Team.create(id: 16, external_id: 8466,  abbreviation: 'sou', name: 'Southampton',              short_name: "So'ton")
Team.create(id: 17, external_id: 8586,  abbreviation: 'tot', name: 'Tottenham Hotspur',        short_name: 'Tottenham')
Team.create(id: 18, external_id: 9817,  abbreviation: 'wat', name: 'Watford',                  short_name: 'Watford')
Team.create(id: 19, external_id: 8654,  abbreviation: 'wha', name: 'West Ham Utd',             short_name: 'West Ham')
Team.create(id: 20, external_id: 8602,  abbreviation: 'wol', name: 'Wolverhampton Wanderers',  short_name: 'Wolves')
